#!/bin/bash
# configure-dhcp-relay.sh — Configure the dedicated MemLabs dnsmasq relay.
#
# Required environment:
#   RELAY_MAPPINGS_B64  base64 of zero or more LF-delimited rows:
#                       <client-interface>|<client-ipv4>|<target-dp-ipv4>
#
# The script provides no DNS, address allocation, TFTP, or PXE options. Windows
# DHCP on the host remains the lease server; dnsmasq relays only to target DPs.
set -euo pipefail

UNIT_NAME=memlabs-dhcp-relay.service
CONFIG_PATH=/etc/memlabs-dhcp-relay.conf
UNIT_PATH="/etc/systemd/system/$UNIT_NAME"
STATE_DIR=/var/lib/memlabs

if [ -z "${RELAY_MAPPINGS_B64+x}" ]; then
    echo "[dhcp-relay] ERROR: RELAY_MAPPINGS_B64 is required" >&2
    exit 2
fi

if ! command -v dnsmasq >/dev/null 2>&1; then
    echo "[dhcp-relay] dnsmasq-base is absent (older Server image); installing runtime fallback"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y dnsmasq-base tcpdump
fi

mkdir -p "$STATE_DIR"
chmod 0755 "$STATE_DIR"
MAPPINGS_FILE=$(mktemp)
CONFIG_NEW=$(mktemp)
UNIT_NEW=$(mktemp)
trap 'rm -f "$MAPPINGS_FILE" "$CONFIG_NEW" "$UNIT_NEW"' EXIT
printf '%s' "$RELAY_MAPPINGS_B64" | base64 -d > "$MAPPINGS_FILE"

# Empty desired state stops the application-level relay. Keep the unit file for
# diagnostics and future reconciliation, but do not claim readiness.
if ! grep -q '[^[:space:]]' "$MAPPINGS_FILE"; then
    systemctl disable --now "$UNIT_NAME" >/dev/null 2>&1 || true
    rm -f "$CONFIG_PATH"
    echo "[dhcp-relay] zero active mappings; service stopped"
    exit 0
fi

cat > "$CONFIG_NEW" <<'EOF'
# Generated by MemLabs. Do not edit.
port=0
no-resolv
no-hosts
log-dhcp
log-facility=-
bind-dynamic
EOF

MAPPING_COUNT=0
SEEN_LOCAL='|'
while IFS='|' read -r client_if client_ip target_ip extra; do
    [ -z "${client_if}${client_ip}${target_ip}${extra}" ] && continue
    if [ -n "$extra" ] || [ -z "$client_if" ] || [ -z "$client_ip" ] || [ -z "$target_ip" ]; then
        echo "[dhcp-relay] ERROR: malformed mapping row" >&2
        exit 2
    fi
    if ! [[ "$client_if" =~ ^[a-zA-Z0-9_.:-]+$ ]]; then
        echo "[dhcp-relay] ERROR: invalid client interface '$client_if'" >&2
        exit 2
    fi
    for address in "$client_ip" "$target_ip"; do
        IFS=. read -r octet1 octet2 octet3 octet4 trailing <<< "$address"
        if [ -n "${trailing:-}" ] || [ -z "${octet4:-}" ]; then
            echo "[dhcp-relay] ERROR: invalid IPv4 address '$address'" >&2
            exit 2
        fi
        for octet in "$octet1" "$octet2" "$octet3" "$octet4"; do
            if ! [[ "$octet" =~ ^[0-9]+$ ]] || [ "$octet" -gt 255 ]; then
                echo "[dhcp-relay] ERROR: invalid IPv4 address '$address'" >&2
                exit 2
            fi
        done
    done
    if ! ip -4 -o address show dev "$client_if" | awk '{print $4}' | grep -qx "$client_ip/24"; then
        echo "[dhcp-relay] ERROR: $client_if does not own exactly $client_ip/24" >&2
        exit 3
    fi
    if [[ "$SEEN_LOCAL" == *"|$client_ip|"* ]]; then
        echo "[dhcp-relay] ERROR: duplicate client address '$client_ip'" >&2
        exit 2
    fi
    SEEN_LOCAL="${SEEN_LOCAL}${client_ip}|"
    printf 'interface=%s\n' "$client_if" >> "$CONFIG_NEW"
    printf 'dhcp-relay=%s,%s\n' "$client_ip" "$target_ip" >> "$CONFIG_NEW"
    MAPPING_COUNT=$((MAPPING_COUNT + 1))
done < "$MAPPINGS_FILE"

if [ "$MAPPING_COUNT" -eq 0 ]; then
    echo "[dhcp-relay] ERROR: mapping payload contained no usable rows" >&2
    exit 2
fi

# This VM is an application-level DHCP relay, never an IP router.
printf 'net.ipv4.ip_forward=0\n' > /etc/sysctl.d/90-memlabs-dhcp-relay.conf
sysctl -q -p /etc/sysctl.d/90-memlabs-dhcp-relay.conf
if [ "$(sysctl -n net.ipv4.ip_forward)" != "0" ]; then
    echo "[dhcp-relay] ERROR: net.ipv4.ip_forward is not 0" >&2
    exit 3
fi

chmod 0644 "$CONFIG_NEW"
/usr/sbin/dnsmasq --test --conf-file="$CONFIG_NEW"

cat > "$UNIT_NEW" <<EOF
[Unit]
Description=MemLabs DHCP relay for ConfigMgr PXE
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/sbin/dnsmasq --keep-in-foreground --pid-file= --conf-file=$CONFIG_PATH
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
chmod 0644 "$UNIT_NEW"

CONFIG_CHANGED=1
UNIT_CHANGED=1
if [ -f "$CONFIG_PATH" ] && cmp -s "$CONFIG_NEW" "$CONFIG_PATH"; then CONFIG_CHANGED=0; fi
if [ -f "$UNIT_PATH" ] && cmp -s "$UNIT_NEW" "$UNIT_PATH"; then UNIT_CHANGED=0; fi
if [ "$CONFIG_CHANGED" -eq 1 ]; then mv "$CONFIG_NEW" "$CONFIG_PATH"; fi
if [ "$UNIT_CHANGED" -eq 1 ]; then mv "$UNIT_NEW" "$UNIT_PATH"; fi

if [ "$UNIT_CHANGED" -eq 1 ]; then systemctl daemon-reload; fi
systemctl enable "$UNIT_NAME" >/dev/null
if systemctl is-active --quiet "$UNIT_NAME"; then
    if [ "$CONFIG_CHANGED" -eq 1 ] || [ "$UNIT_CHANGED" -eq 1 ]; then
        systemctl restart "$UNIT_NAME"
    fi
else
    systemctl start "$UNIT_NAME"
fi

# Preserve an administrator's decision to keep UFW inactive. Add narrowly
# scoped rules only when it is already enforcing policy.
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q '^Status: active'; then
    while IFS='|' read -r client_if client_ip target_ip extra; do
        [ -z "${client_if}${client_ip}${target_ip}${extra}" ] && continue
        ufw allow in on "$client_if" to "$client_ip" port 67 proto udp >/dev/null
        ufw allow out on "$client_if" from "$client_ip" to any port 68 proto udp >/dev/null
    done < "$MAPPINGS_FILE"
fi

systemctl is-enabled --quiet "$UNIT_NAME"
systemctl is-active --quiet "$UNIT_NAME"
if ! ss -H -lunp | grep -Eq '(^|[[:space:]])[^[:space:]]*:67[[:space:]]'; then
    echo "[dhcp-relay] ERROR: service is active but UDP/67 is not listening" >&2
    journalctl -u "$UNIT_NAME" --no-pager -n 30 >&2 || true
    exit 4
fi

echo "[dhcp-relay] relay configuration is ready ($MAPPING_COUNT mapping(s)); UDP/67 listener validated"
