#!/bin/bash
# configure-dhcp-server.sh — atomically apply complete MemLabs DHCP state.
set -euo pipefail

: "${DHCP_STATE_B64:?DHCP_STATE_B64 is required}"

UNIT_NAME=memlabs-dhcp.service
CONFIG_PATH=/etc/memlabs-dhcp.conf
HOSTS_PATH=/etc/memlabs-dhcp-hosts.conf
UNIT_PATH="/etc/systemd/system/$UNIT_NAME"
STATE_DIR=/var/lib/memlabs-dhcp
STATE_PATH="$STATE_DIR/applied-state.json"
LEASE_PATH="$STATE_DIR/dnsmasq.leases"

if ! command -v dnsmasq >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y dnsmasq-base
fi
if ! command -v python3 >/dev/null 2>&1; then
    echo "[dhcp-server] ERROR: python3 is required" >&2
    exit 2
fi

mkdir -p "$STATE_DIR"
chmod 0755 "$STATE_DIR"
STATE_NEW=$(mktemp "$STATE_DIR/state.XXXXXX")
CONFIG_NEW=$(mktemp /etc/memlabs-dhcp.XXXXXX)
HOSTS_NEW=$(mktemp /etc/memlabs-dhcp-hosts.XXXXXX)
UNIT_NEW=$(mktemp /etc/memlabs-dhcp-unit.XXXXXX)
trap 'rm -f "$STATE_NEW" "$CONFIG_NEW" "$HOSTS_NEW" "$UNIT_NEW"' EXIT
printf '%s' "$DHCP_STATE_B64" | base64 -d > "$STATE_NEW"

python3 - "$STATE_NEW" "$CONFIG_NEW" "$HOSTS_NEW" <<'PY'
import ipaddress
import json
import pathlib
import re
import sys

state_path, config_path, hosts_path = map(pathlib.Path, sys.argv[1:])
try:
    state = json.loads(state_path.read_text(encoding="utf-8"))
except Exception as exc:
    raise SystemExit(f"[dhcp-server] ERROR: invalid state JSON: {exc}")
scopes = state.get("Scopes")
if not isinstance(scopes, list) or not scopes:
    raise SystemExit("[dhcp-server] ERROR: desired state contains no scopes")

mac_re = re.compile(r"^[0-9a-f]{2}(?::[0-9a-f]{2}){5}$")
seen_networks = set()
seen_interfaces = set()
seen_ips = set()
config = [
    "# Generated by MemLabs. Do not edit.",
    "port=0",
    "no-resolv",
    "no-hosts",
    "log-dhcp",
    "log-facility=-",
    "bind-dynamic",
    "dhcp-authoritative",
    "dhcp-ignore-clid",
    "dhcp-leasefile=/var/lib/memlabs-dhcp/dnsmasq.leases",
    "dhcp-hostsfile=/etc/memlabs-dhcp-hosts.conf",
]
hosts = []

for index, scope in enumerate(scopes):
    network = ipaddress.ip_network(str(scope.get("ScopeId", "")) + "/24", strict=False)
    if str(network.network_address) != str(scope.get("ScopeId")):
        raise SystemExit(f"[dhcp-server] ERROR: scope is not a /24 network address: {scope.get('ScopeId')}")
    if str(network) in seen_networks:
        raise SystemExit(f"[dhcp-server] ERROR: duplicate scope {network.network_address}")
    seen_networks.add(str(network))

    mac = str(scope.get("InterfaceMac", "")).lower().replace("-", ":")
    if not mac_re.fullmatch(mac):
        raise SystemExit(f"[dhcp-server] ERROR: invalid interface MAC for {network.network_address}: {mac}")
    iface = ""
    wanted = mac.replace(":", "")
    for address_file in pathlib.Path("/sys/class/net").glob("*/address"):
        actual = address_file.read_text().strip().lower().replace(":", "")
        if actual == wanted:
            iface = address_file.parent.name
            break
    if not iface:
        raise SystemExit(f"[dhcp-server] ERROR: interface MAC {mac} for {network.network_address} is absent")
    if iface in seen_interfaces:
        raise SystemExit(f"[dhcp-server] ERROR: interface {iface} assigned to multiple scopes")
    seen_interfaces.add(iface)

    local_ip = ipaddress.ip_address(scope.get("ServerAddress"))
    start = ipaddress.ip_address(scope.get("StartRange"))
    end = ipaddress.ip_address(scope.get("EndRange"))
    if local_ip not in network or start not in network or end not in network or int(start) > int(end):
        raise SystemExit(f"[dhcp-server] ERROR: invalid addresses for scope {network.network_address}")
    tag = f"ml{index}"
    config.extend([
        f"interface={iface}",
        f"dhcp-range=set:{tag},{start},{end},255.255.255.0,365d",
    ])

    router = str(scope.get("Router") or "")
    dns = [str(x) for x in (scope.get("DnsServers") or []) if str(x)]
    domain = str(scope.get("DomainName") or "")
    wins = str(scope.get("WinsServer") or "")
    if router:
        ipaddress.ip_address(router)
        config.append(f"dhcp-option=tag:{tag},option:router,{router}")
    else:
        config.append(f"dhcp-option=tag:{tag},option:router")
    if dns:
        for address in dns:
            ipaddress.ip_address(address)
        config.append(f"dhcp-option=tag:{tag},option:dns-server,{','.join(dns)}")
    else:
        config.append(f"dhcp-option=tag:{tag},option:dns-server")
    if domain:
        if not re.fullmatch(r"[A-Za-z0-9.-]+", domain):
            raise SystemExit(f"[dhcp-server] ERROR: invalid domain {domain!r}")
        config.append(f"dhcp-option=tag:{tag},option:domain-name,{domain}")
    if wins:
        ipaddress.ip_address(wins)
        config.append(f"dhcp-option=tag:{tag},44,{wins}")

    for reservation in scope.get("Reservations") or []:
        rmac = str(reservation.get("MacAddress", "")).lower().replace("-", ":")
        rip = ipaddress.ip_address(reservation.get("IPAddress"))
        if not mac_re.fullmatch(rmac) or rip not in network:
            raise SystemExit(f"[dhcp-server] ERROR: invalid reservation {rmac}/{rip} in {network.network_address}")
        if str(rip) in seen_ips:
            raise SystemExit(f"[dhcp-server] ERROR: duplicate reservation address {rip}")
        seen_ips.add(str(rip))
        hosts.append(f"{rmac},{rip},infinite")

config_path.write_text("\n".join(config) + "\n", encoding="utf-8")
hosts_path.write_text("\n".join(sorted(set(hosts))) + ("\n" if hosts else ""), encoding="utf-8")
PY

chmod 0644 "$CONFIG_NEW" "$HOSTS_NEW" "$STATE_NEW"
CONFIG_EXISTED=0; HOSTS_EXISTED=0; UNIT_EXISTED=0; LEASE_EXISTED=0
[ -f "$CONFIG_PATH" ] && CONFIG_EXISTED=1
[ -f "$HOSTS_PATH" ] && HOSTS_EXISTED=1
[ -f "$UNIT_PATH" ] && UNIT_EXISTED=1
[ -f "$LEASE_PATH" ] && LEASE_EXISTED=1
touch "$HOSTS_PATH"
chmod 0644 "$HOSTS_PATH"
/usr/sbin/dnsmasq --test --conf-file="$CONFIG_NEW"

cat > "$UNIT_NEW" <<EOF
[Unit]
Description=MemLabs authoritative DHCP service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/sbin/dnsmasq --keep-in-foreground --pid-file= --conf-file=$CONFIG_PATH
ExecReload=/bin/kill -HUP \$MAINPID
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
chmod 0644 "$UNIT_NEW"

systemctl disable --now dnsmasq.service >/dev/null 2>&1 || true
CONFIG_CHANGED=1
HOSTS_CHANGED=1
UNIT_CHANGED=1
if [ -f "$CONFIG_PATH" ] && cmp -s "$CONFIG_NEW" "$CONFIG_PATH"; then CONFIG_CHANGED=0; fi
if [ -f "$HOSTS_PATH" ] && cmp -s "$HOSTS_NEW" "$HOSTS_PATH"; then HOSTS_CHANGED=0; fi
if [ -f "$UNIT_PATH" ] && cmp -s "$UNIT_NEW" "$UNIT_PATH"; then UNIT_CHANGED=0; fi

BACKUP_DIR=$(mktemp -d "$STATE_DIR/rollback.XXXXXX")
[ "$CONFIG_EXISTED" -eq 1 ] && cp -a "$CONFIG_PATH" "$BACKUP_DIR/config"
[ "$HOSTS_EXISTED" -eq 1 ] && cp -a "$HOSTS_PATH" "$BACKUP_DIR/hosts"
[ "$UNIT_EXISTED" -eq 1 ] && cp -a "$UNIT_PATH" "$BACKUP_DIR/unit"
[ "$LEASE_EXISTED" -eq 1 ] && cp -a "$LEASE_PATH" "$BACKUP_DIR/leases"
ROLLBACK_ARMED=1
finish_apply() {
    rc=$?
    trap - EXIT
    if [ "$ROLLBACK_ARMED" -eq 1 ]; then
        set +e
        if [ "$CONFIG_EXISTED" -eq 1 ]; then cp -a "$BACKUP_DIR/config" "$CONFIG_PATH"; else rm -f "$CONFIG_PATH"; fi
        if [ "$HOSTS_EXISTED" -eq 1 ]; then cp -a "$BACKUP_DIR/hosts" "$HOSTS_PATH"; else rm -f "$HOSTS_PATH"; fi
        if [ "$UNIT_EXISTED" -eq 1 ]; then cp -a "$BACKUP_DIR/unit" "$UNIT_PATH"; else rm -f "$UNIT_PATH"; fi
        if [ "$LEASE_EXISTED" -eq 1 ]; then cp -a "$BACKUP_DIR/leases" "$LEASE_PATH"; else rm -f "$LEASE_PATH"; fi
        systemctl daemon-reload >/dev/null 2>&1
        if [ "$UNIT_EXISTED" -eq 1 ]; then systemctl restart "$UNIT_NAME" >/dev/null 2>&1; else systemctl disable --now "$UNIT_NAME" >/dev/null 2>&1; fi
        echo "[dhcp-server] ERROR: apply failed; previous configuration restored" >&2
    fi
    rm -rf "$BACKUP_DIR"
    rm -f "$STATE_NEW" "$CONFIG_NEW" "$HOSTS_NEW" "$UNIT_NEW"
    exit "$rc"
}
trap finish_apply EXIT

if [ "$CONFIG_CHANGED" -eq 1 ]; then mv "$CONFIG_NEW" "$CONFIG_PATH"; fi
if [ "$HOSTS_CHANGED" -eq 1 ]; then mv "$HOSTS_NEW" "$HOSTS_PATH"; fi
if [ "$UNIT_CHANGED" -eq 1 ]; then mv "$UNIT_NEW" "$UNIT_PATH"; fi

# A rebuilt VM has a new MAC. If its desired IP is still leased to the old MAC,
# dnsmasq gives the rebuilt VM a dynamic address even though hostsfile contains
# the new reservation. Stop the service before editing its lease database and
# remove rows conflicting by reserved MAC OR reserved IP. The next DORA then
# receives both the reserved address and current DNS/router options.
if [ "$HOSTS_CHANGED" -eq 1 ] && [ -s "$LEASE_PATH" ]; then
    systemctl stop "$UNIT_NAME" >/dev/null 2>&1 || true
    python3 - "$HOSTS_PATH" "$LEASE_PATH" <<'PY'
import pathlib
import sys

hosts_path, lease_path = map(pathlib.Path, sys.argv[1:3])
reserved_macs = set()
reserved_ips = set()
for raw in hosts_path.read_text(encoding="utf-8").splitlines():
    parts = [part.strip().lower() for part in raw.split(",")]
    if len(parts) >= 2:
        reserved_macs.add(parts[0])
        reserved_ips.add(parts[1])

kept = []
for raw in lease_path.read_text(encoding="utf-8").splitlines():
    parts = raw.split()
    if len(parts) >= 3 and (parts[1].lower() in reserved_macs or parts[2].lower() in reserved_ips):
        continue
    kept.append(raw)
lease_path.write_text("\n".join(kept) + ("\n" if kept else ""), encoding="utf-8")
PY
fi

# Preserve an administrator's choice to leave UFW inactive. If it is active,
# open DHCP only on interfaces named by the validated desired state.
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q '^Status: active'; then
    python3 - "$STATE_NEW" <<'PY' | while IFS='|' read -r iface server_ip; do
import json, pathlib, sys
state = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
for scope in state["Scopes"]:
    wanted = str(scope["InterfaceMac"]).lower().replace("-", "").replace(":", "")
    for p in pathlib.Path("/sys/class/net").glob("*/address"):
        if p.read_text().strip().lower().replace(":", "") == wanted:
            print(f"{p.parent.name}|{scope['ServerAddress']}")
            break
PY
        [ -n "$iface" ] || continue
        ufw allow in on "$iface" to "$server_ip" port 67 proto udp >/dev/null
        ufw allow out on "$iface" from "$server_ip" to any port 68 proto udp >/dev/null
    done
fi

if [ "$UNIT_CHANGED" -eq 1 ]; then systemctl daemon-reload; fi
systemctl enable "$UNIT_NAME" >/dev/null
if systemctl is-active --quiet "$UNIT_NAME"; then
    if [ "$CONFIG_CHANGED" -eq 1 ] || [ "$HOSTS_CHANGED" -eq 1 ] || [ "$UNIT_CHANGED" -eq 1 ]; then
        systemctl restart "$UNIT_NAME"
    fi
else
    systemctl start "$UNIT_NAME"
fi

systemctl is-active --quiet "$UNIT_NAME"
DHCP_LISTENING=0
for _attempt in $(seq 1 20); do
    if ss -H -lunp | grep -Eq '(^|[[:space:]])[^[:space:]]*:67[[:space:]]'; then
        DHCP_LISTENING=1
        break
    fi
    sleep 0.5
done
if [ "$DHCP_LISTENING" -ne 1 ]; then
    echo "[dhcp-server] ERROR: service is active but UDP/67 is not listening" >&2
    journalctl -u "$UNIT_NAME" --no-pager -n 40 >&2 || true
    exit 4
fi

python3 - "$STATE_NEW" <<'PY'
import json, pathlib, subprocess, sys
state = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8"))
for scope in state["Scopes"]:
    wanted = str(scope["InterfaceMac"]).lower().replace("-", "").replace(":", "")
    iface = None
    for p in pathlib.Path("/sys/class/net").glob("*/address"):
        if p.read_text().strip().lower().replace(":", "") == wanted:
            iface = p.parent.name
            break
    if not iface:
        raise SystemExit(f"[dhcp-server] ERROR: interface disappeared for {scope['ScopeId']}")
    output = subprocess.check_output(["ip", "-4", "-o", "address", "show", "dev", iface], text=True)
    if f" {scope['ServerAddress']}/24 " not in f" {output} ":
        raise SystemExit(f"[dhcp-server] ERROR: {iface} does not own {scope['ServerAddress']}/24")
print(f"DHCP_SERVER_READY scopes={len(state['Scopes'])} reservations={sum(len(s.get('Reservations') or []) for s in state['Scopes'])}")
PY
mv "$STATE_NEW" "$STATE_PATH"
ROLLBACK_ARMED=0
trap - EXIT
rm -rf "$BACKUP_DIR"
rm -f "$CONFIG_NEW" "$HOSTS_NEW" "$UNIT_NEW"
