<#
.SYNOPSIS
    Reproduces the add-new-VM collision that selected an existing OSD VM.
#>
[CmdletBinding()]
param ([string] $RootPath)

$ErrorActionPreference = 'Stop'
if (-not $RootPath) { $RootPath = Split-Path -Parent $PSScriptRoot }
$script:Failures = 0

function Assert-Equal {
    param($Expected, $Actual, [string]$What)
    $passed = "$Expected" -eq "$Actual"
    if (-not $passed) { $script:Failures++ }
    Write-Host ('{0}  {1}' -f $(if ($passed) { 'PASS' } else { 'FAIL' }), $What)
    if (-not $passed) { Write-Host "      expected: $Expected`n      actual:   $Actual" }
}

function Import-TestFunction {
    param([string]$Path, [string]$Name)
    $errors = $null; $tokens = $null
    $ast = [Management.Automation.Language.Parser]::ParseFile($Path, [ref]$tokens, [ref]$errors)
    if (@($errors).Count) { throw "$Path has parse errors" }
    $definition = @($ast.FindAll({ param($node) $node -is [Management.Automation.Language.FunctionDefinitionAst] -and $node.Name -eq $Name }, $true))
    if ($definition.Count -ne 1) { throw "Expected one $Name definition" }
    [scriptblock]::Create($definition[0].Extent.Text)
}
function Write-Log { param($Message, [switch]$Failure, [switch]$LogOnly) }
function Get-VM {
    [CmdletBinding()]
    param([string]$Name)
    if ($Name -in $script:LiveNames) { return [pscustomobject]@{ Name = $Name } }
}
function Get-NewMachineName {
    param($ConfigToCheck, $vm)
    if ($script:ForceRepeatedName) { return 'OSD1' }
    if ($vm.role -in @('CAS', 'Primary', 'Secondary')) {
        if ([string]::IsNullOrWhiteSpace($vm.siteCode)) {
            $vm.siteCode = Get-NewSiteCode -Role $vm.role -ConfigToCheck $ConfigToCheck
        }
        return "$($vm.siteCode)SITE"
    }
    for ($i = 1; $i -lt 100; $i++) {
        $candidate = "OSD$i"
        if ($candidate -notin @($ConfigToCheck.virtualMachines.vmName)) { return $candidate }
    }
}
function Get-NewSiteCode {
    param($Domain, $Role, $ConfigToCheck)
    $prefix = switch ($Role) {
        'CAS' { 'CS' }
        'Secondary' { 'SS' }
        default { 'PS' }
    }
    for ($i = 1; $i -lt 10; $i++) {
        $candidate = "$prefix$i"
        if ($candidate -notin @($ConfigToCheck.virtualMachines.siteCode)) { return $candidate }
    }
}
function get-PrefixForDomain { param($Domain) 'DER-' }

$sourcePath = Join-Path $RootPath 'common\Common.GenConfig.AddVM.ps1'
$source = Get-Content -LiteralPath $sourcePath -Raw
. (Import-TestFunction $sourcePath 'Resolve-AvailableNewVmName')
$script:ForceRepeatedName = $false
Assert-Equal $true ($source.Contains('$menuCollision = @($ExistingMachines')) 'autogenerated names check the menu inventory'
Assert-Equal $true ($source.Contains('Get-VM -Name $deployedCandidate -ErrorAction SilentlyContinue')) 'autogenerated names check the prefixed live Hyper-V name'
Assert-Equal $true ($source.Contains('$NamingConfig.virtualMachines += [pscustomobject]@{ vmName = $candidate }')) 'collisions are reserved before generating the next suffix'
Assert-Equal $true ($source.Contains("aborting instead of selecting an existing VM")) 'repeated generator output aborts instead of returning a collision'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'example.test'; prefix = 'LAB-' }; virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'OSDClient' }
$script:LiveNames = @()
$resolved = Resolve-AvailableNewVmName -InitialName 'OSD1' -NamingConfig $naming `
    -Domain 'example.test' -TargetConfig $target -VM $vm -Role OSDClient `
    -ExistingMachines @([pscustomobject]@{ vmName = 'LAB-OSD1' })
Assert-Equal 'OSD2' $resolved 'a menu-only OSD1 collision advances to OSD2'
Assert-Equal 'OSD1' $naming.virtualMachines[0].vmName 'the colliding OSD1 name is reserved exactly once'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'example.test'; prefix = 'LAB-' }; virtualMachines = @([pscustomobject]@{ vmName = 'OSD1' }) }
$naming = [pscustomobject]@{ virtualMachines = @() }
$script:LiveNames = @('LAB-OSD2')
$resolved = Resolve-AvailableNewVmName -InitialName 'OSD1' -NamingConfig $naming `
    -Domain 'example.test' -TargetConfig $target -VM $vm -Role OSDClient -ExistingMachines @()
Assert-Equal 'OSD3' $resolved 'config OSD1 plus live Hyper-V OSD2 advances to OSD3'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'example.test'; prefix = 'LAB-' }; virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'Primary'; siteCode = 'PS1' }
$script:LiveNames = @()
$resolved = Resolve-AvailableNewVmName -InitialName 'PS1SITE' -NamingConfig $naming `
    -Domain 'example.test' -TargetConfig $target -VM $vm -Role Primary `
    -ExistingMachines @([pscustomobject]@{ vmName = 'LAB-PS1SITE'; role = 'Primary'; siteCode = 'PS1' })
Assert-Equal 'PS2SITE' $resolved 'a deployed PS1 Primary collision advances to PS2SITE'
Assert-Equal 'PS2' $vm.siteCode 'the Primary site code advances with its generated VM name'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'example.test'; prefix = 'LAB-' }; virtualMachines = @([pscustomobject]@{ vmName = 'CS1SITE'; role = 'CAS'; siteCode = 'CS1' }) }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'CAS'; siteCode = 'CS1' }
$resolved = Resolve-AvailableNewVmName -InitialName 'CS1SITE' -NamingConfig $naming `
    -Domain 'example.test' -TargetConfig $target -VM $vm -Role CAS -ExistingMachines @()
Assert-Equal 'CS2SITE' $resolved 'a config CS1 CAS collision advances to CS2SITE'
Assert-Equal 'CS2' $vm.siteCode 'the CAS site code advances with its generated VM name'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'example.test'; prefix = 'LAB-' }; virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'Secondary'; siteCode = 'SS1' }
$script:LiveNames = @('LAB-SS1SITE')
$resolved = Resolve-AvailableNewVmName -InitialName 'SS1SITE' -NamingConfig $naming `
    -Domain 'example.test' -TargetConfig $target -VM $vm -Role Secondary -ExistingMachines @()
Assert-Equal 'SS2SITE' $resolved 'a live SS1 Secondary collision advances to SS2SITE'
Assert-Equal 'SS2' $vm.siteCode 'the Secondary site code advances with its generated VM name'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'example.test'; prefix = 'LAB-' }; virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'OSDClient' }
$script:LiveNames = @()
$script:ForceRepeatedName = $true
$resolved = Resolve-AvailableNewVmName -InitialName 'OSD1' -NamingConfig $naming `
    -Domain 'example.test' -TargetConfig $target -VM $vm -Role OSDClient `
    -ExistingMachines @([pscustomobject]@{ vmName = 'LAB-OSD1' })
$script:ForceRepeatedName = $false
Assert-Equal $true ([string]::IsNullOrWhiteSpace($resolved)) 'repeated generator output aborts without returning a collision'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'example.test'; prefix = 'LAB-' }; virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @(1..9 | ForEach-Object { [pscustomobject]@{ vmName = "PS$($_)SITE"; siteCode = "PS$_" } }) }
$vm = [pscustomobject]@{ role = 'Primary'; siteCode = 'PS1' }
$resolved = Resolve-AvailableNewVmName -InitialName 'PS1SITE' -NamingConfig $naming `
    -Domain 'example.test' -TargetConfig $target -VM $vm -Role Primary `
    -ExistingMachines @([pscustomobject]@{ vmName = 'LAB-PS1SITE'; role = 'Primary'; siteCode = 'PS1' })
Assert-Equal $true ([string]::IsNullOrWhiteSpace($resolved)) 'site-code exhaustion aborts without returning a collision'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'example.test'; prefix = 'LAB-' }; virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'Primary'; siteCode = 'PS1' }
$script:LiveNames = @('PS1SITE')
$resolved = Resolve-AvailableNewVmName -InitialName 'PS1SITE' -NamingConfig $naming `
    -Domain 'example.test' -TargetConfig $target -VM $vm -Role Primary `
    -ExistingMachines @([pscustomobject]@{ vmName = 'PS1SITE'; role = 'Primary'; siteCode = 'PS1' })
Assert-Equal 'PS1SITE' $resolved 'an unprefixed deployed VM does not collide with LAB-PS1SITE'
Assert-Equal 'PS1' $vm.siteCode 'a false unprefixed collision does not advance the site code'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'TEMPLATE2222.com'; prefix = 'TEM-' }; virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'Primary'; siteCode = 'PS1' }
$script:LiveNames = @()
$resolved = Resolve-AvailableNewVmName -InitialName 'PS1SITE' -NamingConfig $naming `
    -Domain 'derived.test' -TargetConfig $target -VM $vm -Role Primary `
    -ExistingMachines @([pscustomobject]@{ vmName = 'DER-PS1SITE'; role = 'Primary'; siteCode = 'PS1' })
Assert-Equal 'PS2SITE' $resolved 'a new domain replaces the template prefix before collision checks'
Assert-Equal 'PS2' $vm.siteCode 'a template-prefix collision advances the Primary site code'

$target = [pscustomobject]@{ vmOptions = [pscustomobject]@{ domainName = 'prefixfree.test'; prefix = '' }; virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'Primary'; siteCode = 'PS1' }
$resolved = Resolve-AvailableNewVmName -InitialName 'PS1SITE' -NamingConfig $naming `
    -Domain 'prefixfree.test' -TargetConfig $target -VM $vm -Role Primary `
    -ExistingMachines @([pscustomobject]@{ vmName = 'PS1SITE'; role = 'Primary'; siteCode = 'PS1' })
Assert-Equal 'PS2SITE' $resolved 'a same-domain blank prefix remains intentionally blank'
Assert-Equal 'PS2' $vm.siteCode 'a genuine prefix-free collision advances the Primary site code'

if ($script:Failures) { Write-Host "$script:Failures check(s) failed."; exit 1 }
Write-Host 'All GenConfig new-VM collision checks passed.'