<#
.SYNOPSIS
    Reproduces the add-new-VM collision that selected an existing OSD VM.
#>
[CmdletBinding()]
param ([string] $RootPath)

$ErrorActionPreference = 'Stop'
if (-not $RootPath) { $RootPath = Split-Path -Parent $PSScriptRoot }
$script:Failures = 0

function Assert-Equal {
    param($Expected, $Actual, [string]$What)
    $passed = "$Expected" -eq "$Actual"
    if (-not $passed) { $script:Failures++ }
    Write-Host ('{0}  {1}' -f $(if ($passed) { 'PASS' } else { 'FAIL' }), $What)
    if (-not $passed) { Write-Host "      expected: $Expected`n      actual:   $Actual" }
}

function Import-TestFunction {
    param([string]$Path, [string]$Name)
    $errors = $null; $tokens = $null
    $ast = [Management.Automation.Language.Parser]::ParseFile($Path, [ref]$tokens, [ref]$errors)
    if (@($errors).Count) { throw "$Path has parse errors" }
    $definition = @($ast.FindAll({ param($node) $node -is [Management.Automation.Language.FunctionDefinitionAst] -and $node.Name -eq $Name }, $true))
    if ($definition.Count -ne 1) { throw "Expected one $Name definition" }
    [scriptblock]::Create($definition[0].Extent.Text)
}
function Write-Log { param($Message, [switch]$Failure, [switch]$LogOnly) }
function Get-VM {
    [CmdletBinding()]
    param([string]$Name)
    if ($Name -in $script:LiveNames) { return [pscustomobject]@{ Name = $Name } }
}
function Get-NewMachineName {
    param($ConfigToCheck, $vm)
    for ($i = 1; $i -lt 100; $i++) {
        $candidate = "OSD$i"
        if ($candidate -notin @($ConfigToCheck.virtualMachines.vmName)) { return $candidate }
    }
}

$sourcePath = Join-Path $RootPath 'common\Common.GenConfig.AddVM.ps1'
$source = Get-Content -LiteralPath $sourcePath -Raw
. (Import-TestFunction $sourcePath 'Resolve-AvailableNewVmName')
Assert-Equal $true ($source.Contains('$menuCollision = @($ExistingMachines')) 'autogenerated names check the menu inventory'
Assert-Equal $true ($source.Contains('Get-VM -Name $candidate -ErrorAction SilentlyContinue')) 'autogenerated names check live Hyper-V'
Assert-Equal $true ($source.Contains('$NamingConfig.virtualMachines += [pscustomobject]@{ vmName = $candidate }')) 'collisions are reserved before generating the next suffix'
Assert-Equal $true ($source.Contains("aborting instead of selecting an existing VM")) 'repeated generator output aborts instead of returning a collision'

$target = [pscustomobject]@{ virtualMachines = @() }
$naming = [pscustomobject]@{ virtualMachines = @() }
$vm = [pscustomobject]@{ role = 'OSDClient' }
$script:LiveNames = @()
$resolved = Resolve-AvailableNewVmName -InitialName 'OSD1' -NamingConfig $naming `
    -TargetConfig $target -VM $vm -Role OSDClient `
    -ExistingMachines @([pscustomobject]@{ vmName = 'OSD1' })
Assert-Equal 'OSD2' $resolved 'a menu-only OSD1 collision advances to OSD2'
Assert-Equal 'OSD1' $naming.virtualMachines[0].vmName 'the colliding OSD1 name is reserved exactly once'

$target = [pscustomobject]@{ virtualMachines = @([pscustomobject]@{ vmName = 'OSD1' }) }
$naming = [pscustomobject]@{ virtualMachines = @() }
$script:LiveNames = @('OSD2')
$resolved = Resolve-AvailableNewVmName -InitialName 'OSD1' -NamingConfig $naming `
    -TargetConfig $target -VM $vm -Role OSDClient -ExistingMachines @()
Assert-Equal 'OSD3' $resolved 'config OSD1 plus live Hyper-V OSD2 advances to OSD3'

if ($script:Failures) { Write-Host "$script:Failures check(s) failed."; exit 1 }
Write-Host 'All GenConfig new-VM collision checks passed.'