function Rename-VirtualMachine {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "Base Property Object")]
        [Object] $vm,
        [Parameter(Mandatory = $false, HelpMessage = "NewName - AutoGenerated if blank")]
        [string] $newName
    )

    if ($vm.ExistingVM) {
        return
    }
    $rename = $true
    if (-not $newName) {
        $rename = $false
        $newName = Get-NewMachineName -vm $vm
        if ($($vm.vmName) -ne $newName) {
            $rename = $true
            Write-Log -Activity "Proposing to rename $($vm.vmName) to $($newName) due to configuration changes" -NoNewLine
            $response = Read-YesOrNoWithTimeout -Prompt "Rename $($vm.vmName) to $($newName)? (Y/n)" -HideHelp -Default "y"
            if (-not [String]::IsNullOrWhiteSpace($response)) {
                if ($response.ToLowerInvariant() -eq "n" -or $response.ToLowerInvariant() -eq "no") {
                    $rename = $false
                }
            }
        }
    }

    if ($rename -eq $true) {

        foreach ($existing in $Global:Config.virtualMachines) {
            if ($existing.RemoteSQLVM -eq $vm.vmName) {
                $existing.RemoteSQLVM = $newName
            }
            if ($existing.remoteContentLibVM -eq $vm.vmName) {
                $existing.remoteContentLibVM = $newName
            }
            if ($existing.patchMyPCFileServer -eq $vm.vmName) {
                $existing.patchMyPCFileServer = $newName
            }
            if ($existing.FileServerVM -eq $vm.vmName) {
                $existing.FileServerVM = $newName
            }
            if ($existing.pullDPSourceDP -eq $vm.vmName) {
                $existing.pullDPSourceDP = $newName
            }
            if ($existing.wsusDataBaseServer -eq $vm.vmName) {
                $existing.wsusDataBaseServer = $newName
            }


        }
        $vm.vmName = $newName
        return $newName
    }

}


function Get-NetworkForVM {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "VM Object")]
        [object] $vm,
        [Parameter(Mandatory = $false, HelpMessage = "Config to Modify")]
        [object] $ConfigToModify = $global:config,
        [Parameter(Mandatory = $false, HelpMessage = "If a new network isn't needed, return null")]
        [bool] $ReturnIfNotNeeded = $false
    )

    $currentNetwork = $ConfigToModify.vmOptions.Network
    if ($currentNetwork -eq "10.234.241.0") {
        return
    }
    if ($vm.Network) {
        $currentNetwork = $vm.Network
    }
    $SiteServers = get-list2 -deployConfig $ConfigToModify | Where-Object { ($_.Role -eq "Primary" -or $_.Role -eq "Secondary") -and $_.vmName -ne $vm.vmName }
    #$SiteServers | convertto-Json | Out-Host
    #$ConfigToModify  |convertto-Json | Out-Host
    #$Secondaries = get-list2 -deployConfig $ConfigToModify  | Where-Object {$_.Role -eq "Secondary"}
    switch ($vm.role) {
        "Secondary" {
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "Primary" {
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "CAS" {
            $SiteServers = get-list2 -deployConfig $ConfigToModify | Where-Object { ($_.Role -eq "Primary" -or $_.Role -eq "Secondary" -or $_.Role -eq "CAS") -and $_.vmName -ne $vm.vmName }
            $SiteServers = $SiteServers | Where-Object { -not ($_.Role -eq "Primary" -and $_.ParentSiteCode -eq $vm.SiteCode) }
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "PassiveSite" {
            $SS = Get-SiteServerForSiteCode -siteCode $vm.SiteCode -deployConfig $ConfigToModify -type VM
            if ($ss.network -ne $currentNetwork) {
                return $ss.Network
            }
        }
        Default {
            if (-not $ReturnIfNotNeeded) {
                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm

            }
        }
    }

    return $null
}

function Add-NewVMForRole {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "Role")]
        [String] $Role,
        [Parameter(Mandatory = $true, HelpMessage = "Domain Name")]
        [String] $Domain,
        [Parameter(Mandatory = $false, HelpMessage = "Config to Modify")]
        [object] $ConfigToModify = $global:config,
        [Parameter(Mandatory = $false, HelpMessage = "Force VM Name. Otherwise auto-generated")]
        [string] $Name = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Force VM Name for 2nd Node. Otherwise auto-generated")]
        [string] $Name2 = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Parent Side Code if this is a Primary or Secondary in a Hierarchy")]
        [string] $parentSiteCode = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Override Network")]
        [string] $network = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Site Code if this is a PassiveSite or a DPMP")]
        [string] $SiteCode = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Override default OS")]
        [string] $OperatingSystem = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Return Created Machine Name")]
        [bool] $ReturnMachineName = $false,
        [Parameter(Mandatory = $false, HelpMessage = "Quiet Mode")]
        [bool] $Quiet = $false,
        [Parameter(Mandatory = $false, HelpMessage = "Test Mode")]
        [bool] $test = $false,
        [Parameter(Mandatory = $false, HelpMessage = "True if this is the Secondary SQLAO Node")]
        [bool] $secondSQLAO = $false
    )


    $oldConfig = $configToModify | ConvertTo-Json -Depth 5 | ConvertFrom-Json
    Write-Verbose "[Add-NewVMForRole] Start Role: $Role Domain: $Domain Config: $ConfigToModify OS: $OperatingSystem SiteCode: $SiteCode ParentSiteCode: $parentSiteCode Network: $network"

    if ([string]::IsNullOrWhiteSpace($OperatingSystem)) {
        if ($role -eq "WorkgroupMember" -or $role -eq "AADClient" -or $role -eq "InternetClient") {
            $OSList = Get-SupportedOperatingSystemsForRole -role $role
            $operatingSystem = "Windows 10 Latest (64-bit)"
            if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                $operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
            }
            else {          
                Write-Log -Verbose "No Default OS defined" 
                $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM"  -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false -CurrentValue $operatingSystem
                if ($OperatingSystem -eq "ESCAPE") {
                    return
                }
            }
        }
        else {
            if ($role -eq "Linux") {
                $OSList = Get-SupportedOperatingSystemsForRole -role $role
                if ($null -eq $OSList ) {
                    $OperatingSystem = "Linux Unknown"
                }
                else {
                    Write-Log -Activity "OS Version selection for new '$role' VM" -NoNewLine
                    $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM" -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false
                    if ($OperatingSystem -eq "ESCAPE") {
                        return
                    }
                }
            }
            else {
                $OSList = Get-SupportedOperatingSystemsForRole -role $role
                if ($role.Contains("Client")) {
                    $DefaultOperatingSystem = "Windows 10 Latest (64-bit)"
                    if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                        $operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
                    }
                }
                else {
                    $DefaultOperatingSystem = "Server 2022"
                    if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                        $operatingSystem = $ConfigToModify.domainDefaults.DefaultServerOS
                    }
                }
                if ($null -ne $OSList) {
                    if (-not $OperatingSystem) {                        
                        Write-Log -Verbose "No Default OS defined" 
                        Write-Log -Activity "OS Version selection for new '$role' VM" -NoNewLine
                        $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM" -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false -CurrentValue $DefaultOperatingSystem
                        if ($OperatingSystem -eq "ESCAPE") {
                            $OperatingSystem = $DefaultOperatingSystem
                            return
                        }
                    }
                }
            }
        }
    }


    $actualRoleName = ($Role -split " ")[0]

    if ($role -eq "SqlServer") {
        $actualRoleName = "DomainMember"
    }

    $memory = "2GB"
    $vprocs = 2

    $installSSMS = $false
    if ($OperatingSystem.Contains("Server") -and ($role -notin ("DC", "BDC"))) {
        $memory = "3GB"
        $vprocs = 4
        $installSSMS = $true
        if ($ConfigToModify.domainDefaults.IncludeSSMSOnNONSQL -eq $false) {
            $installSSMS = $false
            if ($role -eq "SqlServer") {
                $installSSMS = $true
            }
        }
    }
    if ($OperatingSystem.Contains("Windows 11") -and ($role -notin ("DC", "BDC"))) {
        $memory = "4GB"
        
        $installSSMS = $false
    }

    if ($role -eq "Linux") {
        $virtualMachine = [PSCustomObject]@{
            vmName          = $null
            role            = $actualRoleName
            operatingSystem = $OperatingSystem
            memory          = $memory
            virtualProcs    = $vprocs
            vmGeneration    = 1
        }
    }
    else {
        $virtualMachine = [PSCustomObject]@{
            vmName          = $null
            role            = $actualRoleName
            operatingSystem = $OperatingSystem
            memory          = $memory
            virtualProcs    = $vprocs
            tpmEnabled      = $true
        }
    }

    if ($network) {
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
    }
    if ($role -notin ("OSDClient", "AADClient", "DC", "BDC", "Linux")) {
        #Match Windows 10 or 11
        if ($operatingSystem.Contains("Windows 1")) {
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'useFakeWSUSServer' -Value $false -force
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $installSSMS -force
    }

   

    $existingDPMP = $null
    $NewFSServer = $null
    switch ($Role) {
        "WSUS" {
            $virtualMachine.Memory = "6GB"
            #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $true
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'wsusContentDir' -Value "E:\WSUS" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            #if (-not $SiteCode) {
            #    $SiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
            #    if ($test) {
            #        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            #    }
            #    else {
            #        Get-SiteCodeMenu -property $virtualMachine -name "siteCode" -CurrentValue $SiteCode -ConfigToCheck $configToModify
            #        if (-not $virtualMachine.SiteCode) {
            #            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $false -force
            #        }
            #    }
            #}
            #else {
            #    #write-log "Adding new DPMP for sitecode $newSiteCode"
            #    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            #}

        }
        "SqlServer" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion  -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "E:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.Memory = "7GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $virtualMachine.tpmEnabled = $false
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value "LocalSystem" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value "LocalSystem" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
        }
        "SQLAO" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "E:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.Memory = "7GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $virtualMachine.tpmEnabled = $false
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force

        }
        "CAS" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "F:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value "E:\ConfigMgr" -force
            $disk = [PSCustomObject]@{"E" = "250GB"; "F" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installRP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr CAS" -force
            $virtualMachine.Memory = "10GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem   
            if (-not $test) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }                
            }
        }
        "Primary" {
            if ($parentSiteCode) {
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'parentSiteCode' -Value $parentSiteCode
            }
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "F:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value "E:\ConfigMgr" -force
            $disk = [PSCustomObject]@{"E" = "600GB"; "F" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installRP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr Primary Site" -force

            $virtualMachine.Memory = "10GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $existingDPMP = ($ConfigToModify.virtualMachines | Where-Object { $_.installDP -or $_.enablePullDP } | Measure-Object).Count
            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }

        }
        "Secondary" {
            $virtualMachine.memory = "3GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'parentSiteCode' -Value $parentSiteCode -force
            $virtualMachine.operatingSystem = $OperatingSystem
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value 'E:\ConfigMgr' -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr Secondary Site" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }

        }
        "PassiveSite" {
            $virtualMachine.memory = "3GB"
            $NewFSServer = $true
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value 'E:\ConfigMgr' -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force

            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }
        }
        "WorkgroupMember" {}
        "InternetClient" {}
        "AADClient" {}
        "StandaloneRootCA" {
            $virtualMachine.Memory = "2GB"
            $virtualMachine.virtualProcs = 2
        }
        "DomainMember" {
            if ($OperatingSystem -notlike "*Server*") {
                $users = get-list2 -DeployConfig $oldConfig | Where-Object { $_.domainUser } | Select-Object -ExpandProperty domainUser -Unique
                [int]$i = 1
                $userPrefix = $oldConfig.vmOptions.prefix.toLower() + "user"
                $userNoPrefix = "user"
                while ($true) {
                    $preferredUserName = $userPrefix + $i
                    $noPrefixUserName = $userNoPrefix + $i
                    if ($users -contains $preferredUserName -or $users -contains $noPrefixUserName) {
                        write-log -verbose "$preferredUserName already exists Trying next"
                        $i++
                    }
                    else {
                        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'domainUser' -Value $noPrefixUserName -force
                        break
                    }
                }
            }
        }
        "DomainMember (Server)" {}
        "DomainMember (Client)" {
            if ($OperatingSystem -like "*Server*") {
                if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                    $virtualMachine.operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
                }
                else {
                    $virtualMachine.operatingSystem = "Windows 10 Latest (64-bit)"
                }
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'useFakeWSUSServer' -Value $false -force
            }
            else {
                $virtualMachine.operatingSystem = $OperatingSystem
            }

            $users = get-list2 -DeployConfig $oldConfig | Where-Object { $_.domainUser } | Select-Object -ExpandProperty domainUser -Unique
            [int]$i = 1
            $userPrefix = $oldConfig.vmOptions.prefix.toLower() + "user"
            $userNoPrefix = "user"
            while ($true) {
                $preferredUserName = $userPrefix + $i
                $noPrefixUserName = $userNoPrefix + $i
                if ($users -contains $preferredUserName -or $users -contains $noPrefixUserName) {
                    write-log -verbose "$preferredUserName already exists Trying next"
                    $i++
                }
                else {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'domainUser' -Value $noPrefixUserName -force
                    break
                }

            }

            $virtualMachine.Memory = "2GB"
            if ($virtualMachine.operatingSystem.Contains("Windows 11") ) {
                $virtualMachine.Memory = "4GB"
            }
        }
        "OSDClient" {
            $virtualMachine.memory = "2GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'vmGeneration' -Value "2" -force
            $virtualMachine.PsObject.Members.Remove('operatingSystem')
        }
        "SiteSystem" {
            $virtualMachine.memory = "4GB"
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallDP' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallMP' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallSUP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallRP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallSMSProv' -Value $false -force
            if (-not $SiteCode) {
                $SiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
                if ($test) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
                }
                else {
                    #This sets the virtualmachine.Sitecode property.. Make sure to read this back in when done.
                    Get-SiteCodeMenu -property $virtualMachine -name "siteCode" -CurrentValue $SiteCode -ConfigToCheck $configToModify -test:$false
                }

                if (-not $($virtualMachine.SiteCode)) {
                    Write-RedX "Could not add SiteCode to SiteSystem $($virtualMachine.vmName). Cancelling"
                    return
                }

                if ((get-RoleForSitecode -ConfigToCheck $ConfigToModify -siteCode $virtualMachine.siteCode) -eq "CAS") {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installDP' -Value $false -force
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installMP' -Value $false -force
                }

                if ($virtualMachine.installDP) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'enablePullDP' -Value $false
                }
            }
            else {
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            }
            # Needed when expanding an existing domain
            $siteCode = $virtualMachine.siteCode
            if ((get-RoleForSitecode -ConfigToCheck $ConfigToModify -siteCode $siteCode) -eq "Secondary") {
                $virtualMachine.installMP = $false
            }
        }
        "FileServer" {
            $virtualMachine.memory = "3GB"
            $disk = [PSCustomObject]@{"E" = "600GB"; "F" = "200GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.tpmEnabled = $false
        }
        "DC" {
            $virtualMachine.memory = "4GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallCA' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'UseOfflineRoot' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'ForestTrust' -Value "NONE" -force
            $virtualMachine.tpmEnabled = $false
        }
        "BDC" {
            $virtualMachine.memory = "4GB"
            $virtualMachine.tpmEnabled = $false
        }
    }

    if ([string]::IsNullOrWhiteSpace($Name)) {
        if ($virtualMachine.InstallMP -or $virtualMachine.InstallDP) {
            $machineName = Get-NewMachineName -ConfigToCheck $oldConfig -vm $virtualMachine
        }
        else {
            $machineName = Get-NewMachineName -ConfigToCheck $oldConfig -vm $virtualMachine
        }
        Write-Verbose "Machine Name Generated $machineName"
    }
    else {
        $machineName = $Name
    }
    $virtualMachine.vmName = $machineName

    if ($null -eq $ConfigToModify.VirtualMachines) {
        $ConfigToModify | Add-Member -MemberType NoteProperty -Name "VirtualMachines" -Value @() -Force
    }
    
    if ($ConfigToModify.domainDefaults.UseDynamicMemory) {
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'dynamicMinRam' -Value "1GB" -force
    }
    else {
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'dynamicMinRam' -Value $virtualMachine.memory -force
    }

    # Before adding, check if a VM with this name already exists
    $existingVM = $ConfigToModify.VirtualMachines | Where-Object { $_.vmName -eq $virtualMachine.vmName }
    if ($existingVM) {
        Write-Log -verbose "A VM with the name '$($virtualMachine.vmName)' already exists. Skipping add."
        if ($ReturnMachineName) {
            return $virtualMachine.vmName
        }
        else {
            return
        }
    }
    $ConfigToModify.virtualMachines += $virtualMachine

    if ($role -eq "Primary" -or $role -eq "CAS" -or $role -eq "PassiveSite" -or $role -eq "SiteSystem" -or $role -eq "Secondary") {
        if ($null -eq $ConfigToModify.cmOptions) {
            $latestVersion = Get-CMLatestBaselineVersion
            $newCmOptions = [PSCustomObject]@{
                Version                   = $latestVersion
                Install                   = $true
                PushClientToDomainMembers = $true
                PrePopulateObjects        = $true
                EVALVersion               = $false
                #InstallSCP                = $true
                OfflineSCP                = $false
                OfflineSUP                = $false
                UsePKI                    = $false
            }
            $ConfigToModify | Add-Member -MemberType NoteProperty -Name 'cmOptions' -Value $newCmOptions -force
        }
    }

    if ($role -eq "CAS") {
        Add-NewVMForRole -Role Primary -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -Quiet:$Quiet -parentSiteCode $virtualMachine.SiteCode -network:$virtualMachine.network
    }

    #if ($existingPrimary -gt 0) {
    #    ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).parentSiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "CAS" } | Select-Object -First 1).siteCode
    #}

    if ($existingDPMP -eq 0) {
        if (-not $newSiteCode) {
            $newSiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
        }
        if (-not $test) {
            Write-Host "New Primary server found. Adding new DPMP for sitecode $newSiteCode"
        }
        Add-NewVMForRole -Role SiteSystem -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -SiteCode $newSiteCode -Quiet:$Quiet
    }
    if ($Role -eq "PassiveSite") {
        $SiteCode = $virtualMachine.SiteCode

        $primaryNode = $ConfigToModify.virtualMachines | Where-Object { $_.Role -in ("Primary", "CAS") -and $_.siteCode -eq $SiteCode }
        if ($primaryNode.Role -eq "Primary") {                 
            $DPsForSiteCode = $ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "SiteSystem" -and $_.siteCode -eq $SiteCode -and $_.installDP -eq $true }
            if (-not $DPsForSiteCode) {
                Add-NewVMForRole -Role SiteSystem -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -SiteCode $SiteCode -Quiet:$Quiet
            }
        }
    }
    if ($Role -eq "SQLAO" -and (-not $secondSQLAO)) {
        write-host "$($virtualMachine.VmName) is the 1st SQLAO"
        $SQLAONode = Add-NewVMForRole -Role SQLAO -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -Name $Name2 -secondSQLAO:$true -Quiet:$Quiet -ReturnMachineName:$true -network:$network
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'OtherNode' -Value $SQLAONode -force
        if ($test -eq $false ) {
            $FSName = select-FileServerMenu -ConfigToModify $ConfigToModify -HA:$false
            if ($FSName -eq "ESCAPE") {
                Remove-VMFromConfig -vmName $virtualMachine.vmName -ConfigToModify $ConfigToModify
                Remove-VMFromConfig -vmName $SQLAONode -ConfigToModify $ConfigToModify
                return
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'fileServerVM' -Value $FSName -force
        }
        #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'SQLAgentAccount' -Value "SqlAgentUser"
        #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value "SqlServiceUser"
        $ClusterName = Get-NewMachineName -vm $virtualMachine -ConfigToCheck $ConfigToModify -ClusterName:$true -SkipOne:$true
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'ClusterName' -Value $ClusterName -force
        $AOName = Get-NewMachineName -vm $virtualMachine -ConfigToCheck $ConfigToModify -AOName:$true -SkipOne:$true
        $AGName = "SQL"
        if ($SiteCode) {
            $AGName = $siteCode
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'AlwaysOnGroupName' -Value $($AGName + " Availability Group") -force
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'AlwaysOnListenerName' -Value $AOName -force

        $ServiceAccount = "$($ClusterName)Svc"
        $AgentAccount = "$($ClusterName)Agent"

        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value $ServiceAccount -force
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value $AgentAccount -force

        $otherNode = $ConfigToModify.VirtualMachines | Where-Object { $_.vmName -eq $SQLAONode }
        $otherNode | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value $ServiceAccount -force
        $otherNode | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value $AgentAccount -force


    }
    if ($NewFSServer -eq $true) {
        #Get-PSCallStack | out-host
        $FSName = select-FileServerMenu -ConfigToModify $ConfigToModify -HA:$true
        if ($FSName -eq "ESCAPE") {
            Remove-VMFromConfig -vmName $virtualMachine.vmName -ConfigToModify $ConfigToModify
            return
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'remoteContentLibVM' -Value $FSName
    }
    #Get-PSCallStack | out-host
    if (-not $Quiet) {
        Write-Host2 -ForegroundColor $Global:Common.Colors.GenConfigNotice "New Virtual Machine $machineName ($role) was added"
    }
    Write-verbose "[Add-NewVMForRole] Config: $ConfigToModify"
    if ($ReturnMachineName) {
        return $machineName
    }
}

function Add-OfflineRootCAVMIfMissing {
    # When any DC has UseOfflineRoot = $true but no Standalone Offline
    # Root CA exists - neither in the in-memory config nor already deployed
    # in the target domain - auto-add one so the user doesn't have to.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.vmOptions -or -not $ConfigToModify.vmOptions.domainName) { return }

    # Only proceed if a DC has UseOfflineRoot enabled
    $dcOptionEnabled = @($ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'DC' -and $_.InstallCA -and $_.UseOfflineRoot }).Count -gt 0
    if (-not $dcOptionEnabled) { return }

    $existsInConfig = @($ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'StandaloneRootCA' }).Count -gt 0
    if ($existsInConfig) { return }

    $domainName = $ConfigToModify.vmOptions.domainName
    try {
        $existsInDomain = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | Where-Object { $_.role -eq 'StandaloneRootCA' }).Count -gt 0
        if ($existsInDomain) { return }
    } catch {}

    write-log "[OfflineRootCA] DC UseOfflineRoot enabled but no StandaloneRootCA VM found - auto-adding one to domain $domainName"
    $existingNames = @($ConfigToModify.virtualMachines | ForEach-Object { $_.vmName })
    $rootOS = if ($ConfigToModify.domainDefaults.DefaultServerOS) { $ConfigToModify.domainDefaults.DefaultServerOS } else { 'Server 2022' }
    Add-NewVMForRole -Role 'StandaloneRootCA' -Domain $domainName -ConfigToModify $ConfigToModify -OperatingSystem $rootOS -Quiet:$true | Out-Null
    # Tag the VM we just added so Remove-OfflineRootCAVMIfAutoAdded can
    # safely auto-remove it later if the user toggles UseOfflineRoot off.
    # We never tag a user-created VM, so manual additions are preserved.
    $newVM = $ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'StandaloneRootCA' -and $existingNames -notcontains $_.vmName } | Select-Object -First 1
    if ($newVM) {
        $newVM | Add-Member -MemberType NoteProperty -Name '_autoAddedByOfflineRootCA' -Value $true -Force
    }
}

function Remove-OfflineRootCAVMIfAutoAdded {
    # Counterpart to Add-OfflineRootCAVMIfMissing: when no DC has
    # UseOfflineRoot enabled, remove any StandaloneRootCA VM that we
    # previously auto-added. We only remove VMs tagged with
    # _autoAddedByOfflineRootCA, so user-created Root CA VMs are preserved.
    # We also skip removal if the VM is already deployed in the domain.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.virtualMachines) { return }
    # Only auto-remove when no DC wants an offline root.
    $dcOptionOn = @($ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'DC' -and $_.InstallCA -and $_.UseOfflineRoot }).Count -gt 0
    if ($dcOptionOn) { return }

    $domainName = if ($ConfigToModify.vmOptions) { $ConfigToModify.vmOptions.domainName } else { $null }
    $deployedNames = @()
    if ($domainName) {
        try {
            $deployedNames = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | ForEach-Object { $_.vmName })
        } catch {}
    }

    $toRemove = @($ConfigToModify.virtualMachines | Where-Object {
        $_.role -eq 'StandaloneRootCA' -and
        $_.PSObject.Properties['_autoAddedByOfflineRootCA'] -and
        $_._autoAddedByOfflineRootCA -and
        ($deployedNames -notcontains $_.vmName)
    })
    foreach ($vm in $toRemove) {
        write-log "[OfflineRootCA] UseOfflineRoot disabled - auto-removing previously auto-added StandaloneRootCA VM '$($vm.vmName)'"
        Remove-VMFromConfig -vmName $vm.vmName -ConfigToModify $ConfigToModify
    }
}
