# This file must be saved with UTF-8 BOM. createGuestDscZip.ps1 loads it under PS 5.1, which needs the BOM to parse Unicode.
function Rename-VirtualMachine {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "Base Property Object")]
        [Object] $vm,
        [Parameter(Mandatory = $false, HelpMessage = "NewName - AutoGenerated if blank")]
        [string] $newName
    )

    if ($vm.ExistingVM) {
        return
    }
    $rename = $true
    if (-not $newName) {
        $rename = $false
        $newName = Get-NewMachineName -vm $vm
        if ($($vm.vmName) -ne $newName) {
            $rename = $true
            Write-Log -Activity "Proposing to rename $($vm.vmName) to $($newName) due to configuration changes" -NoNewLine
            $response = Read-YesOrNoWithTimeout -Prompt "Rename $($vm.vmName) to $($newName)? (Y/n)" -HideHelp -Default "y"
            if (-not [String]::IsNullOrWhiteSpace($response)) {
                if ($response.ToLowerInvariant() -eq "n" -or $response.ToLowerInvariant() -eq "no") {
                    $rename = $false
                }
            }
        }
    }

    if ($rename -eq $true) {

        foreach ($existing in $Global:Config.virtualMachines) {
            if ($existing.RemoteSQLVM -eq $vm.vmName) {
                $existing.RemoteSQLVM = $newName
            }
            if ($existing.remoteContentLibVM -eq $vm.vmName) {
                $existing.remoteContentLibVM = $newName
            }
            if ($existing.patchMyPCFileServer -eq $vm.vmName) {
                $existing.patchMyPCFileServer = $newName
            }
            if ($existing.FileServerVM -eq $vm.vmName) {
                $existing.FileServerVM = $newName
            }
            if ($existing.pullDPSourceDP -eq $vm.vmName) {
                $existing.pullDPSourceDP = $newName
            }
            if ($existing.wsusDataBaseServer -eq $vm.vmName) {
                $existing.wsusDataBaseServer = $newName
            }


        }
        $vm.vmName = $newName
        return $newName
    }

}


function Get-NetworkForVM {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "VM Object")]
        [object] $vm,
        [Parameter(Mandatory = $false, HelpMessage = "Config to Modify")]
        [object] $ConfigToModify = $global:config,
        [Parameter(Mandatory = $false, HelpMessage = "If a new network isn't needed, return null")]
        [bool] $ReturnIfNotNeeded = $false
    )

    $currentNetwork = $ConfigToModify.vmOptions.Network
    if ($currentNetwork -eq "10.234.241.0") {
        return
    }
    if ($vm.Network) {
        $currentNetwork = $vm.Network
    }
    $SiteServers = get-list2 -deployConfig $ConfigToModify | Where-Object { ($_.Role -eq "Primary" -or $_.Role -eq "Secondary") -and $_.vmName -ne $vm.vmName }
    #$SiteServers | convertto-Json | Out-Host
    #$ConfigToModify  |convertto-Json | Out-Host
    #$Secondaries = get-list2 -deployConfig $ConfigToModify  | Where-Object {$_.Role -eq "Secondary"}
    switch ($vm.role) {
        "Secondary" {
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "Primary" {
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "CAS" {
            $SiteServers = get-list2 -deployConfig $ConfigToModify | Where-Object { ($_.Role -eq "Primary" -or $_.Role -eq "Secondary" -or $_.Role -eq "CAS") -and $_.vmName -ne $vm.vmName }
            $SiteServers = $SiteServers | Where-Object { -not ($_.Role -eq "Primary" -and $_.ParentSiteCode -eq $vm.SiteCode) }
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "PassiveSite" {
            $SS = Get-SiteServerForSiteCode -siteCode $vm.SiteCode -deployConfig $ConfigToModify -type VM
            if ($ss.network -ne $currentNetwork) {
                return $ss.Network
            }
        }
        "SiteSystem" {
            # sitesAndNetworks maps exactly one subnet per site code, so a DP/MP left
            # on the default network sits inside another site's boundary.
            # Get-SiteServerForSiteCode throws when the site code resolves to nothing.
            try {
                $SS = Get-SiteServerForSiteCode -siteCode $vm.SiteCode -deployConfig $ConfigToModify -type VM
            }
            catch {
                Write-Log "Get-NetworkForVM: no site server found for site code '$($vm.SiteCode)'; leaving $($vm.vmName) on $currentNetwork." -LogOnly
                return $null
            }
            if ($ss.network -ne $currentNetwork) {
                return $ss.Network
            }
        }
        Default {
            if (-not $ReturnIfNotNeeded) {
                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm

            }
        }
    }

    return $null
}

function Add-NewVMForRole {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "Role")]
        [String] $Role,
        [Parameter(Mandatory = $true, HelpMessage = "Domain Name")]
        [String] $Domain,
        [Parameter(Mandatory = $false, HelpMessage = "Config to Modify")]
        [object] $ConfigToModify = $global:config,
        [Parameter(Mandatory = $false, HelpMessage = "Force VM Name. Otherwise auto-generated")]
        [string] $Name = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Force VM Name for 2nd Node. Otherwise auto-generated")]
        [string] $Name2 = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Parent Side Code if this is a Primary or Secondary in a Hierarchy")]
        [string] $parentSiteCode = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Override Network")]
        [string] $network = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Site Code if this is a PassiveSite or a DPMP")]
        [string] $SiteCode = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Override default OS")]
        [string] $OperatingSystem = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Return Created Machine Name")]
        [bool] $ReturnMachineName = $false,
        [Parameter(Mandatory = $false, HelpMessage = "Quiet Mode")]
        [bool] $Quiet = $false,
        [Parameter(Mandatory = $false, HelpMessage = "Test Mode")]
        [bool] $test = $false,
        [Parameter(Mandatory = $false, HelpMessage = "True if this is the Secondary SQLAO Node")]
        [bool] $secondSQLAO = $false
    )


    $oldConfig = $configToModify | ConvertTo-Json -Depth 5 | ConvertFrom-Json
    Write-Verbose "[Add-NewVMForRole] Start Role: $Role Domain: $Domain Config: $ConfigToModify OS: $OperatingSystem SiteCode: $SiteCode ParentSiteCode: $parentSiteCode Network: $network"

    if ([string]::IsNullOrWhiteSpace($OperatingSystem)) {
        if ($role -eq "Proxy") {
            # Proxy is always Linux (Ubuntu) -- no OS choice.
            $OperatingSystem = "Ubuntu Server 24.04 LTS"
        }
        elseif ($role -eq "LinuxServer") {
            # Generic Linux server: same base image as Proxy, DHCP networking.
            $OperatingSystem = "Ubuntu Server 24.04 LTS"
        }
        elseif ($role -eq "LinuxClient") {
            # Ubuntu Desktop workstation (UbuntuDesktop2404.vhdx) -- no OS choice.
            # Without this branch a LinuxClient falls into the final else, where
            # $role.Contains("Client") pre-fills operatingSystem from
            # domainDefaults.DefaultClientOS (a Windows client OS), so a new
            # LinuxClient would show up as Windows 10/11.
            $OperatingSystem = "Ubuntu Desktop 24.04 LTS"
        }
        elseif ($role -eq "WorkgroupMember" -or $role -eq "AADClient" -or $role -eq "InternetClient") {
            $OSList = Get-SupportedOperatingSystemsForRole -role $role
            if (-not $OSList -or $OSList.Count -eq 0) {
                Write-Host
                Write-RedX "No supported operating systems available for role '$role'. If running in Offline Mode, ensure base images are downloaded first."
                return
            }
            $operatingSystem = "Windows 10 Latest (64-bit)"
            if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                if ($OSList -contains $ConfigToModify.domainDefaults.DefaultClientOS) {
                    $operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
                }
                else {
                    Write-Log "Default client OS '$($ConfigToModify.domainDefaults.DefaultClientOS)' is not available (Offline Mode?). Prompting for selection." -Warning
                    $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM" -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false -CurrentValue $operatingSystem
                    if ($OperatingSystem -eq "ESCAPE" -or $OperatingSystem -eq "NOITEMS") {
                        return
                    }
                }
            }
            else {          
                Write-Log -Verbose "No Default OS defined" 
                $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM"  -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false -CurrentValue $operatingSystem
                if ($OperatingSystem -eq "ESCAPE" -or $OperatingSystem -eq "NOITEMS") {
                    return
                }
            }
        }
        else {
            $OSList = Get-SupportedOperatingSystemsForRole -role $role
            if ($role.Contains("Client")) {
                $DefaultOperatingSystem = "Windows 10 Latest (64-bit)"
                if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                    $operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
                }
            }
            else {
                $DefaultOperatingSystem = "Server 2022"
                if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                    $operatingSystem = $ConfigToModify.domainDefaults.DefaultServerOS
                }
            }
            if ($null -ne $OSList) {
                if (-not $OperatingSystem) {                        
                    Write-Log -Verbose "No Default OS defined" 
                    Write-Log -Activity "OS Version selection for new '$role' VM" -NoNewLine
                    $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM" -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false -CurrentValue $DefaultOperatingSystem
                    if ($OperatingSystem -eq "ESCAPE") {
                        $OperatingSystem = $DefaultOperatingSystem
                        return
                    }
                }
            }
        }
    }


    $actualRoleName = ($Role -split " ")[0]

    if ($role -eq "SqlServer") {
        $actualRoleName = "DomainMember"
    }

    $memory = "2GB"
    $vprocs = 2

    $installSSMS = $false
    if ($OperatingSystem.Contains("Server") -and ($role -notin ("DC", "BDC"))) {
        $memory = "3GB"
        $vprocs = 4
        $installSSMS = $true
        if ($ConfigToModify.domainDefaults.IncludeSSMSOnNONSQL -eq $false) {
            $installSSMS = $false
            if ($role -eq "SqlServer") {
                $installSSMS = $true
            }
        }
    }
    if ($OperatingSystem.Contains("Windows 11") -and ($role -notin ("DC", "BDC"))) {
        $memory = "4GB"
        
        $installSSMS = $false
    }

    $virtualMachine = [PSCustomObject]@{
        vmName          = $null
        role            = $actualRoleName
        operatingSystem = $OperatingSystem
        memory          = $memory
        virtualProcs    = $vprocs
        tpmEnabled      = $true
    }

    if ($role -eq "Proxy") {
        # Linux VM: no TPM, lightweight footprint, osFamily marker so
        # Test-VmIsLinux short-circuits the Windows create/validation paths.
        # 2GB/2vCPU is the floor: at 1GB/1vCPU a Proxy booting alongside 20+
        # Windows VMs could fail to reach userspace at all.
        $virtualMachine.PSObject.Properties.Remove('tpmEnabled')
        $virtualMachine.memory = "2GB"
        $virtualMachine.virtualProcs = 2
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'osFamily' -Value 'Linux' -Force
        # Optional xrdp + lightweight desktop for graphical login. When true,
        # New-LinuxVirtualMachine installs xrdp/xfce4 via cloud-init and the
        # RDCMan file includes an entry that auto-logs in as vmbuildadmin
        # using the same LocalAdmin password as the rest of the lab.
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'enableRDP' -Value $false -Force
    }

    if ($role -eq "LinuxServer") {
        # Generic Linux VM: no TPM, DHCP networking (default in New-LinuxSeedIso),
        # slightly larger footprint than Proxy since it's a general-purpose box.
        # osFamily=Linux makes Test-VmIsLinux short-circuit the Windows create/
        # validation paths the same way it does for Proxy.
        $virtualMachine.PSObject.Properties.Remove('tpmEnabled')
        $virtualMachine.memory = "2GB"
        $virtualMachine.virtualProcs = 2
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'osFamily' -Value 'Linux' -Force
        # Optional xrdp + xfce4 desktop (same toggle as Proxy).
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'enableRDP' -Value $false -Force
        # Optional realmd/SSSD join to the lab AD domain on first boot.
        # When true, New-LinuxVirtualMachine adds realmd packages + a
        # `realm join` runcmd to the cloud-init seed ISO. Default false
        # so the VM stands alone unless the user opts in.
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'joinDomain' -Value $false -Force
    }

    if ($role -eq "LinuxClient") {
        # Ubuntu Desktop workstation: real GNOME/GDM3/NetworkManager image
        # (UbuntuDesktop2404.vhdx) targeted at MDM/EDR testing (Intune for
        # Linux, Defender for Endpoint, Landscape, etc.). Heavier footprint
        # than LinuxServer since GNOME wants ~3GB to be usable, and the
        # baked-in xrdp/xorgxrdp service means RDP into a real Ubuntu
            # session works out of the box (no enableRDP cloud-init toggle
            # needed -- the existing toggle installs xfce4 which would clash
            # with GNOME on this image).
        $virtualMachine.PSObject.Properties.Remove('tpmEnabled')
        $virtualMachine.memory = "4GB"
        $virtualMachine.virtualProcs = 4
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'osFamily' -Value 'Linux' -Force
        # Optional realmd/SSSD join to the lab AD domain on first boot
        # (same helper as LinuxServer).
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'joinDomain' -Value $false -Force
    }

    if ($network) {
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
    }
    if ($role -notin ("OSDClient", "AADClient", "DC", "BDC", "Proxy", "LinuxServer", "LinuxClient")) {
        #Match Windows 10 or 11
        if ($operatingSystem.Contains("Windows 1")) {
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'useFakeWSUSServer' -Value $false -force
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $installSSMS -force
    }

   

    $existingDPMP = $null
    $NewFSServer = $null
    switch ($Role) {
        "WSUS" {
            # Default to 8GB: a standalone WSUS uses the Windows Internal Database (WID)
            # co-located with the WsusPool app pool, and the first full catalog sync can
            # push their combined working set past 4-5GB. Below 8GB the pool hits its
            # memory-recycle cap mid-sync and the sync is OOM/recycle-killed (503),
            # which the WID+WSUS memory validation flags as a hard failure. Default to
            # 8GB so a freshly-added WSUS passes validation out of the box.
            $virtualMachine.Memory = "8GB"
            #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $true
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'wsusContentDir' -Value "E:\WSUS" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            #if (-not $SiteCode) {
            #    $SiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
            #    if ($test) {
            #        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            #    }
            #    else {
            #        Get-SiteCodeMenu -property $virtualMachine -name "siteCode" -CurrentValue $SiteCode -ConfigToCheck $configToModify
            #        if (-not $virtualMachine.SiteCode) {
            #            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $false -force
            #        }
            #    }
            #}
            #else {
            #    #write-log "Adding new DPMP for sitecode $newSiteCode"
            #    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            #}

        }
        "SqlServer" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion  -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "E:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.Memory = "7GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $virtualMachine.tpmEnabled = $false
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value "LocalSystem" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value "LocalSystem" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
        }
        "SQLAO" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "E:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.Memory = "7GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $virtualMachine.tpmEnabled = $false
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force

        }
        "CAS" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "F:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value "E:\ConfigMgr" -force
            $disk = [PSCustomObject]@{"E" = "250GB"; "F" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $enableSUP = if ($ConfigToModify.domainDefaults.EnableSUPOnSiteServers) { $true } else { $false }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $enableSUP -force
            if ($enableSUP) {
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'wsusContentDir' -Value "E:\WSUS" -force
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installRP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr CAS" -force
            $virtualMachine.Memory = "10GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem   
            if (-not $test) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }                
            }
        }
        "Primary" {
            if ($parentSiteCode) {
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'parentSiteCode' -Value $parentSiteCode
            }
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "F:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value "E:\ConfigMgr" -force
            $disk = [PSCustomObject]@{"E" = "600GB"; "F" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $enableSUP = if ($ConfigToModify.domainDefaults.EnableSUPOnSiteServers) { $true } else { $false }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $enableSUP -force
            if ($enableSUP) {
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'wsusContentDir' -Value "E:\WSUS" -force
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installRP' -Value $false -force
            # A Primary can optionally host its own DP/MP in addition to dedicated
            # SiteSystem DPs (e.g. to serve as a Pull DP source). Default both off.
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installDP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installMP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr Primary Site" -force

            $virtualMachine.Memory = "10GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $existingDPMP = ($ConfigToModify.virtualMachines | Where-Object { $_.installDP -or $_.enablePullDP } | Measure-Object).Count
            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }

        }
        "Secondary" {
            $virtualMachine.memory = "3GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'parentSiteCode' -Value $parentSiteCode -force
            $virtualMachine.operatingSystem = $OperatingSystem
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value 'E:\ConfigMgr' -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr Secondary Site" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }

        }
        "PassiveSite" {
            $virtualMachine.memory = "3GB"
            $NewFSServer = $true
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value 'E:\ConfigMgr' -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force

            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }
        }
        "WorkgroupMember" {}
        "InternetClient" {}
        "AADClient" {}
        "StandaloneRootCA" {
            $virtualMachine.Memory = "2GB"
            $virtualMachine.virtualProcs = 2
        }
        "DomainMember" {
            if ($OperatingSystem -notlike "*Server*") {
                $users = get-list2 -DeployConfig $oldConfig | Where-Object { $_.domainUser } | Select-Object -ExpandProperty domainUser -Unique
                [int]$i = 1
                $userPrefix = $oldConfig.vmOptions.prefix.toLower() + "user"
                $userNoPrefix = "user"
                while ($true) {
                    $preferredUserName = $userPrefix + $i
                    $noPrefixUserName = $userNoPrefix + $i
                    if ($users -contains $preferredUserName -or $users -contains $noPrefixUserName) {
                        write-log -verbose "$preferredUserName already exists Trying next"
                        $i++
                    }
                    else {
                        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'domainUser' -Value $noPrefixUserName -force
                        break
                    }
                }
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installOffice' -Value $false -force
            }
        }
        "DomainMember (Server)" {}
        "DomainMember (Client)" {
            if ($OperatingSystem -like "*Server*") {
                if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                    $virtualMachine.operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
                }
                else {
                    $virtualMachine.operatingSystem = "Windows 10 Latest (64-bit)"
                }
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'useFakeWSUSServer' -Value $false -force
            }
            else {
                $virtualMachine.operatingSystem = $OperatingSystem
            }

            $users = get-list2 -DeployConfig $oldConfig | Where-Object { $_.domainUser } | Select-Object -ExpandProperty domainUser -Unique
            [int]$i = 1
            $userPrefix = $oldConfig.vmOptions.prefix.toLower() + "user"
            $userNoPrefix = "user"
            while ($true) {
                $preferredUserName = $userPrefix + $i
                $noPrefixUserName = $userNoPrefix + $i
                if ($users -contains $preferredUserName -or $users -contains $noPrefixUserName) {
                    write-log -verbose "$preferredUserName already exists Trying next"
                    $i++
                }
                else {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'domainUser' -Value $noPrefixUserName -force
                    break
                }

            }

            $virtualMachine.Memory = "2GB"
            if ($virtualMachine.operatingSystem.Contains("Windows 11") ) {
                $virtualMachine.Memory = "4GB"
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installOffice' -Value $false -force
        }
        "OSDClient" {
            $virtualMachine.memory = "2GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'vmGeneration' -Value "2" -force
            $virtualMachine.PsObject.Members.Remove('operatingSystem')
        }
        "SiteSystem" {
            $virtualMachine.memory = "4GB"
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallDP' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallMP' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallSUP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallRP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallSMSProv' -Value $false -force
            if (-not $SiteCode) {
                $SiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
                if ($test) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
                }
                else {
                    #This sets the virtualmachine.Sitecode property.. Make sure to read this back in when done.
                    Get-SiteCodeMenu -property $virtualMachine -name "siteCode" -CurrentValue $SiteCode -ConfigToCheck $configToModify -test:$false
                }

                if (-not $($virtualMachine.SiteCode)) {
                    Write-RedX "Could not add SiteCode to SiteSystem $($virtualMachine.vmName). Cancelling"
                    return
                }

                if ((get-RoleForSitecode -ConfigToCheck $ConfigToModify -siteCode $virtualMachine.siteCode) -eq "CAS") {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installDP' -Value $false -force
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installMP' -Value $false -force
                }

                if ($virtualMachine.installDP) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'enablePullDP' -Value $false
                }
            }
            else {
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            }
            # Needed when expanding an existing domain
            $siteCode = $virtualMachine.siteCode
            if ((get-RoleForSitecode -ConfigToCheck $ConfigToModify -siteCode $siteCode) -eq "Secondary") {
                $virtualMachine.installMP = $false
            }
            if (-not $network) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }
        }
        "FileServer" {
            $virtualMachine.memory = "3GB"
            $disk = [PSCustomObject]@{"E" = "600GB"; "F" = "200GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.tpmEnabled = $false
        }
        "DC" {
            $virtualMachine.memory = "4GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'ForestTrust' -Value "NONE" -force
            $virtualMachine.tpmEnabled = $false
        }
        "BDC" {
            $virtualMachine.memory = "4GB"
            $virtualMachine.tpmEnabled = $false
        }
    }

    if ([string]::IsNullOrWhiteSpace($Name)) {
        if ($virtualMachine.InstallMP -or $virtualMachine.InstallDP) {
            $machineName = Get-NewMachineName -ConfigToCheck $oldConfig -vm $virtualMachine
        }
        else {
            $machineName = Get-NewMachineName -ConfigToCheck $oldConfig -vm $virtualMachine
        }
        Write-Verbose "Machine Name Generated $machineName"
    }
    else {
        $machineName = $Name
    }
    $virtualMachine.vmName = $machineName

    if ($null -eq $ConfigToModify.VirtualMachines) {
        $ConfigToModify | Add-Member -MemberType NoteProperty -Name "VirtualMachines" -Value @() -Force
    }

    # Add BitLocker property if BLM is enabled and VM has TPM + client OS.
    # Non-domain roles (InternetClient, WorkgroupMember, AADClient) never receive BLM policy.
    if ($virtualMachine.tpmEnabled -and $ConfigToModify.cmOptions -and $ConfigToModify.cmOptions.EnableBLM -and $role -notin 'InternetClient', 'WorkgroupMember', 'AADClient') {
        $isClientOS = $virtualMachine.operatingSystem -and $virtualMachine.operatingSystem -like "Windows 1*"
        $virtualMachine | Add-Member -MemberType NoteProperty -Name "BitLocker" -Value ([bool]$isClientOS) -Force
    }

    # Add pushClient property for DomainMember and site system VMs.
    # Default from domainDefaults:
    #   client OS DomainMember        -> PushCMClientToClients
    #   server OS DomainMember (+SQL) -> PushCMClientToServers
    #   site system roles             -> PushCMClientToSiteSystems
    # Use the normalized role ($actualRoleName) here, NOT the raw $Role: the
    # role menu passes "DomainMember (Client)" / "DomainMember (Server)" /
    # "SqlServer", all of which normalize to "DomainMember". Gating on the raw
    # $Role silently skipped pushClient for every client (the "(Client)" suffix
    # made '$role -eq DomainMember' false), so the property never appeared.
    $siteSystemRoles = @('Primary', 'CAS', 'Secondary', 'SiteSystem', 'PassiveSite')
    if ($actualRoleName -eq 'DomainMember' -or $actualRoleName -in $siteSystemRoles) {
        # Canonical per-role fallback matching Get-NewDomainDefaults
        # (NewDomain.ps1): Clients ON, Servers OFF, SiteSystems OFF. Site
        # servers install the CM client locally during CM setup, so they are
        # NOT a client-push target by default (a $true fallback here wrongly
        # turned pushClient ON for site servers on domains whose domainDefaults
        # predates the PushCMClientToSiteSystems key).
        if ($actualRoleName -in $siteSystemRoles) {
            $defaultKey = 'PushCMClientToSiteSystems'
            $defaultVal = $false
        }
        else {
            $isClientOS = $virtualMachine.operatingSystem -and $virtualMachine.operatingSystem -like "Windows 1*"
            if ($isClientOS) { $defaultKey = 'PushCMClientToClients'; $defaultVal = $true }
            else { $defaultKey = 'PushCMClientToServers'; $defaultVal = $false }
        }
        if ($ConfigToModify.domainDefaults -and ($null -ne $ConfigToModify.domainDefaults.$defaultKey)) {
            $defaultVal = [bool]$ConfigToModify.domainDefaults.$defaultKey
        }
        # pushClient stores a TARGET SITE CODE string (or $false). Resolve the
        # boolean default to a concrete site code (the site whose subnet matches
        # this VM, else the first Primary) so the new VM is consistent with the
        # site-code model. Falls back to $false / the boolean when no CM site
        # exists yet.
        $pushValue = $defaultVal
        if ($defaultVal) {
            $domForPush = $null
            if ($ConfigToModify.vmOptions) { $domForPush = $ConfigToModify.vmOptions.domainName }
            $eligiblePush = @(Get-EligiblePushSites -Config $ConfigToModify -Domain $domForPush)
            if ($eligiblePush.Count -gt 0) {
                $resolved = Resolve-PushClientSite -VM $virtualMachine -Config $ConfigToModify -Domain $domForPush -EligibleSites $eligiblePush
                if ($resolved) { $pushValue = $resolved } else { $pushValue = $false }
            }
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name "pushClient" -Value $pushValue -Force
    }

    # Add useProxy property for VMs that can sensibly route through the
    # domain's Squid proxy. Excludes the Proxy VM itself, DCs (DNS for the
    # domain itself), and StandaloneRootCA (offline, no networking). Both
    # Windows and Linux VMs are eligible -- Windows clients are configured
    # via Set-WindowsClientProxy over PSDirect, Linux clients via the Phase 3
    # roles/proxy-client bash module over SSH.
    # Default is seeded from one of two domainDefaults keys depending on the
    # VM's purpose:
    #   ConfigMgr site-system roles -> UseProxyForCM
    #   everything else (clients, plain DomainMembers, Linux) -> UseProxyForClients
    $proxyExcluded = @('Proxy', 'DC', 'BDC', 'StandaloneRootCA')
    if ($role -notin $proxyExcluded) {
        $cmRoles = @('CAS', 'Primary', 'Secondary', 'SiteSystem', 'PassiveSite', 'WSUS', 'SQLAO', 'FileServer')
        $useProxyKey = if ($role -in $cmRoles) { 'UseProxyForCM' } else { 'UseProxyForClients' }
        $useProxyDefault = $false
        if ($ConfigToModify.domainDefaults -and ($null -ne $ConfigToModify.domainDefaults.$useProxyKey)) {
            $useProxyDefault = [bool]$ConfigToModify.domainDefaults.$useProxyKey
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name "useProxy" -Value $useProxyDefault -Force
    }

    # Linux VMs run with static memory (Hyper-V Dynamic Memory on Linux is
    # flaky), so dynamicMinRam is meaningless for them -- don't add it.
    if (-not (Test-VmIsLinux -Vm $virtualMachine)) {
        if ($ConfigToModify.domainDefaults.UseDynamicMemory) {
            # SQL workloads need a higher floor; ConfigMgr SQL min server memory is 4GB
            $defaultMin = if ($virtualMachine.sqlVersion) { "4GB" } else { "1GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'dynamicMinRam' -Value $defaultMin -force
        }
        else {
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'dynamicMinRam' -Value $virtualMachine.memory -force
        }
    }

    # Before adding, check if a VM with this name already exists
    $existingVM = $ConfigToModify.VirtualMachines | Where-Object { $_.vmName -eq $virtualMachine.vmName }
    if ($existingVM) {
        Write-Log -verbose "A VM with the name '$($virtualMachine.vmName)' already exists. Skipping add."
        if ($ReturnMachineName) {
            return $virtualMachine.vmName
        }
        else {
            return
        }
    }
    $ConfigToModify.virtualMachines += $virtualMachine

    if ($role -eq "Primary" -or $role -eq "CAS" -or $role -eq "PassiveSite" -or $role -eq "SiteSystem" -or $role -eq "Secondary") {
        # Post-migration shape: cmOptions live on each top-level site server VM
        # (CAS, or standalone Primary). Attach a block to the newly added VM
        # only when it is itself a top-level (CAS or Primary with no
        # parentSiteCode). When another top-level already exists in the
        # config, clone its cmOptions so the new hierarchy starts with the
        # same Version / PKI / BLM settings. Otherwise create defaults.
        # Child Primary under a CAS, SiteSystem, PassiveSite, and Secondary
        # all inherit at deploy time via New-DeployConfig rehydration.
        $isTopLevelAdd = ($role -in 'CAS', 'Primary') -and (-not $virtualMachine.parentSiteCode)
        if ($isTopLevelAdd -and -not $virtualMachine.cmOptions) {
            $existingTopLevel = $ConfigToModify.virtualMachines | Where-Object {
                $_.vmName -ne $virtualMachine.vmName -and
                $_.role -in 'CAS', 'Primary' -and -not $_.parentSiteCode -and $_.cmOptions
            } | Select-Object -First 1
            if ($existingTopLevel) {
                $newCmOptions = $existingTopLevel.cmOptions | ConvertTo-Json -Depth 5 -Compress | ConvertFrom-Json
            }
            else {
                # domainDefaults is a hint only. This is the one valid time to
                # consume it: the new top-level VM has no actual cmOptions yet.
                $latestVersion = Get-CmVersionWithHintFallback -DomainDefaults $ConfigToModify.domainDefaults -FallbackVersion (Get-CMLatestBaselineVersion)
                $newCmOptions = [PSCustomObject]@{
                    Version                   = $latestVersion
                    Install                   = $true
                    PrePopulateObjects        = $true
                    EVALVersion               = $false
                    #InstallSCP                = $true
                    OfflineSCP                = $false
                    OfflineSUP                = $false
                    UsePKI                    = $false
                    EnableBLM                 = $false
                    WsusImportBaseline        = $true
                }
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmOptions' -Value $newCmOptions -force
        }
    }

    if ($role -eq "CAS") {
        Add-NewVMForRole -Role Primary -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -Quiet:$Quiet -parentSiteCode $virtualMachine.SiteCode -network:$virtualMachine.network
    }

    #if ($existingPrimary -gt 0) {
    #    ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).parentSiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "CAS" } | Select-Object -First 1).siteCode
    #}

    if ($existingDPMP -eq 0) {
        if (-not $newSiteCode) {
            $newSiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
        }
        if (-not $test) {
            Write-Host "New Primary server found. Adding new DPMP for sitecode $newSiteCode"
        }
        Add-NewVMForRole -Role SiteSystem -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -SiteCode $newSiteCode -Quiet:$Quiet
    }
    if ($Role -eq "PassiveSite") {
        $SiteCode = $virtualMachine.SiteCode

        $primaryNode = $ConfigToModify.virtualMachines | Where-Object { $_.Role -in ("Primary", "CAS") -and $_.siteCode -eq $SiteCode }
        if ($primaryNode.Role -eq "Primary") {                 
            $DPsForSiteCode = $ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "SiteSystem" -and $_.siteCode -eq $SiteCode -and $_.installDP -eq $true }
            if (-not $DPsForSiteCode) {
                Add-NewVMForRole -Role SiteSystem -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -SiteCode $SiteCode -Quiet:$Quiet
            }
        }
    }
    if ($Role -eq "SQLAO" -and (-not $secondSQLAO)) {
        write-host "$($virtualMachine.VmName) is the 1st SQLAO"
        $SQLAONode = Add-NewVMForRole -Role SQLAO -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -Name $Name2 -secondSQLAO:$true -Quiet:$Quiet -ReturnMachineName:$true -network:$network
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'OtherNode' -Value $SQLAONode -force
        if ($test -eq $false ) {
            $FSName = select-FileServerMenu -ConfigToModify $ConfigToModify -HA:$false
            if ($FSName -eq "ESCAPE") {
                Remove-VMFromConfig -vmName $virtualMachine.vmName -ConfigToModify $ConfigToModify
                Remove-VMFromConfig -vmName $SQLAONode -ConfigToModify $ConfigToModify
                return
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'fileServerVM' -Value $FSName -force
        }
        #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'SQLAgentAccount' -Value "SqlAgentUser"
        #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value "SqlServiceUser"
        $ClusterName = Get-NewMachineName -vm $virtualMachine -ConfigToCheck $ConfigToModify -ClusterName:$true -SkipOne:$true
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'ClusterName' -Value $ClusterName -force
        $AOName = Get-NewMachineName -vm $virtualMachine -ConfigToCheck $ConfigToModify -AOName:$true -SkipOne:$true
        $AGName = "SQL"
        if ($SiteCode) {
            $AGName = $siteCode
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'AlwaysOnGroupName' -Value $($AGName + " Availability Group") -force
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'AlwaysOnListenerName' -Value $AOName -force

        $ServiceAccount = "$($ClusterName)Svc"
        $AgentAccount = "$($ClusterName)Agent"

        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value $ServiceAccount -force
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value $AgentAccount -force

        $otherNode = $ConfigToModify.VirtualMachines | Where-Object { $_.vmName -eq $SQLAONode }
        $otherNode | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value $ServiceAccount -force
        $otherNode | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value $AgentAccount -force


    }
    if ($NewFSServer -eq $true) {
        #Get-PSCallStack | out-host
        $FSName = select-FileServerMenu -ConfigToModify $ConfigToModify -HA:$true
        if ($FSName -eq "ESCAPE") {
            Remove-VMFromConfig -vmName $virtualMachine.vmName -ConfigToModify $ConfigToModify
            return
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'remoteContentLibVM' -Value $FSName
    }
    #Get-PSCallStack | out-host
    if (-not $Quiet) {
        Write-Host2 -ForegroundColor $Global:Common.Colors.GenConfigNotice "New Virtual Machine $machineName ($role) was added"
    }
    Write-verbose "[Add-NewVMForRole] Config: $ConfigToModify"
    if ($ReturnMachineName) {
        return $machineName
    }
}

function Add-OfflineRootCAVMIfMissing {
    # When pkiOptions.UseOfflineRoot is enabled but no Standalone Offline
    # Root CA exists - neither in the in-memory config nor already deployed
    # in the target domain - auto-add one so the user doesn't have to.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.vmOptions -or -not $ConfigToModify.vmOptions.domainName) { return }

    # Only proceed if pkiOptions.UseOfflineRoot is enabled
    $pkiOpts = $ConfigToModify.pkiOptions
    if (-not $pkiOpts -or -not $pkiOpts.UseOfflineRoot) { return }

    $existsInConfig = @($ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'StandaloneRootCA' }).Count -gt 0
    if ($existsInConfig) { return }

    $domainName = $ConfigToModify.vmOptions.domainName
    try {
        $existsInDomain = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | Where-Object { $_.role -eq 'StandaloneRootCA' }).Count -gt 0
        if ($existsInDomain) { return }
    } catch {}

    write-log "[OfflineRootCA] pkiOptions.UseOfflineRoot enabled but no StandaloneRootCA VM found - auto-adding one to domain $domainName"
    $existingNames = @($ConfigToModify.virtualMachines | ForEach-Object { $_.vmName })
    $rootOS = if ($ConfigToModify.domainDefaults.DefaultServerOS) { $ConfigToModify.domainDefaults.DefaultServerOS } else { 'Server 2022' }
    Add-NewVMForRole -Role 'StandaloneRootCA' -Domain $domainName -ConfigToModify $ConfigToModify -OperatingSystem $rootOS -Quiet:$true | Out-Null
    # Tag the VM we just added so Remove-OfflineRootCAVMIfAutoAdded can
    # safely auto-remove it later if the user toggles UseOfflineRoot off.
    # We never tag a user-created VM, so manual additions are preserved.
    $newVM = $ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'StandaloneRootCA' -and $existingNames -notcontains $_.vmName } | Select-Object -First 1
    if ($newVM) {
        $newVM | Add-Member -MemberType NoteProperty -Name '_autoAddedByOfflineRootCA' -Value $true -Force
        # Also update pkiOptions.OfflineRootCAVM if not already set
        if ($pkiOpts -and -not $pkiOpts.OfflineRootCAVM) {
            $pkiOpts.OfflineRootCAVM = $newVM.vmName
        }
        # Drop any stale validation messages referencing this newly-added VM
        # (see Add-ProxyVMIfMissing for the carryOver-staleness rationale).
        Clear-StaleValidationMessagesForVM -VmName $newVM.vmName
    }
}

function Clear-StaleValidationMessagesForVM {
    # Removes any entries from $global:GenConfigErrorMessages and
    # $global:PendingValidationErrors whose Message references the given VM
    # name. Called whenever an auto-add/auto-remove mutates the config so
    # stale messages from a previous validation pass (different config shape)
    # don't surface to the user via the carryOver mechanism in genconfig.ps1.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $VmName
    )

    if (-not $VmName) { return }
    $needle = "[$VmName]"

    if ($global:GenConfigErrorMessages) {
        $kept = @($global:GenConfigErrorMessages | Where-Object { $_.Message -notlike "*$needle*" })
        if ($kept.Count -ne $global:GenConfigErrorMessages.Count) {
            Write-Log "[Clear-StaleValidationMessagesForVM] Dropped $($global:GenConfigErrorMessages.Count - $kept.Count) stale msg(s) for $VmName from GenConfigErrorMessages" -LogOnly
            $global:GenConfigErrorMessages = $kept
        }
    }
    if ($global:PendingValidationErrors) {
        $kept = @($global:PendingValidationErrors | Where-Object { $_.Message -notlike "*$needle*" })
        if ($kept.Count -ne $global:PendingValidationErrors.Count) {
            Write-Log "[Clear-StaleValidationMessagesForVM] Dropped $($global:PendingValidationErrors.Count - $kept.Count) stale msg(s) for $VmName from PendingValidationErrors" -LogOnly
            $global:PendingValidationErrors = $kept
        }
    }
}

function Remove-OfflineRootCAVMIfAutoAdded {
    # Counterpart to Add-OfflineRootCAVMIfMissing: when pkiOptions.UseOfflineRoot
    # is disabled, remove any StandaloneRootCA VM that we previously auto-added.
    # We only remove VMs tagged with _autoAddedByOfflineRootCA, so user-created
    # Root CA VMs are preserved. We also skip removal if the VM is already
    # deployed in the domain.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.virtualMachines) { return }

    # Only auto-remove when pkiOptions.UseOfflineRoot is disabled
    $pkiOpts = $ConfigToModify.pkiOptions
    $offlineRootEnabled = $pkiOpts -and $pkiOpts.UseOfflineRoot
    if ($offlineRootEnabled) { return }

    $domainName = if ($ConfigToModify.vmOptions) { $ConfigToModify.vmOptions.domainName } else { $null }
    $deployedNames = @()
    if ($domainName) {
        try {
            $deployedNames = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | ForEach-Object { $_.vmName })
        } catch {}
    }

    $toRemove = @($ConfigToModify.virtualMachines | Where-Object {
        $_.role -eq 'StandaloneRootCA' -and
        $_.PSObject.Properties['_autoAddedByOfflineRootCA'] -and
        $_._autoAddedByOfflineRootCA -and
        ($deployedNames -notcontains $_.vmName)
    })
    foreach ($vm in $toRemove) {
        write-log "[OfflineRootCA] UseOfflineRoot disabled - auto-removing previously auto-added StandaloneRootCA VM '$($vm.vmName)'"
        Remove-VMFromConfig -vmName $vm.vmName -ConfigToModify $ConfigToModify
    }
}

function Test-ConfigNeedsProxy {
    # Returns $true iff any non-hidden VM in the config has useProxy=$true.
    # domainDefaults.UseProxyFor* are seed-only hints used by Add-NewVMForRole
    # to populate the per-VM useProxy at creation time; they are NOT consulted
    # here. If every VM has useProxy=$false, the config does not need a proxy,
    # regardless of what the domain default says.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [object] $ConfigToModify
    )

    foreach ($vm in @($ConfigToModify.virtualMachines)) {
        if ($vm.hidden) { continue }
        if ($vm.PSObject.Properties.Name -contains 'useProxy' -and [bool]$vm.useProxy) {
            return $true
        }
    }
    return $false
}

function Disable-ProxyOptIn {
    # Clears every proxy opt-in in the config so a Proxy VM the user just
    # deleted is not immediately re-added by Add-ProxyVMIfMissing on the next
    # menu pass. Returns what was flipped so the caller can report it.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    $flipped = New-Object System.Collections.Generic.List[string]
    if (-not $ConfigToModify) { return $flipped.ToArray() }

    foreach ($vm in @($ConfigToModify.virtualMachines)) {
        if (-not $vm) { continue }
        if ($vm.PSObject.Properties.Name -contains 'useProxy' -and [bool]$vm.useProxy) {
            $vm.useProxy = $false
            $flipped.Add([string]$vm.vmName)
        }
    }

    # Seed-only hints: left true, the next VM added would opt in and pull a
    # replacement Proxy VM straight back into the config.
    if ($ConfigToModify.domainDefaults) {
        foreach ($key in @('UseProxyForClients', 'UseProxyForCM')) {
            if ($ConfigToModify.domainDefaults.PSObject.Properties.Name -contains $key -and [bool]$ConfigToModify.domainDefaults.$key) {
                $ConfigToModify.domainDefaults.$key = $false
                $flipped.Add("domainDefaults.$key")
            }
        }
    }

    return $flipped.ToArray()
}

function Add-ProxyVMIfMissing {
    # When the in-memory config opts into the proxy (domainDefaults.UseProxyFor*
    # or any per-VM useProxy=$true) but no Proxy VM exists -- neither in the
    # config nor already deployed in the target domain -- auto-add a Linux
    # Proxy VM so the user doesn't have to. Counterpart to
    # Remove-ProxyVMIfAutoAdded.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.vmOptions -or -not $ConfigToModify.vmOptions.domainName) { return }
    if (-not (Test-ConfigNeedsProxy -ConfigToModify $ConfigToModify)) { return }

    $existsInConfig = @($ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'Proxy' }).Count -gt 0
    if ($existsInConfig) { return }

    $domainName = $ConfigToModify.vmOptions.domainName
    try {
        $existsInDomain = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | Where-Object { $_.role -eq 'Proxy' }).Count -gt 0
        if ($existsInDomain) { return }
    } catch {}

    write-log "[Proxy] Proxy is enabled (domainDefaults or per-VM useProxy) but no Proxy VM found - auto-adding one to domain $domainName"
    $existingNames = @($ConfigToModify.virtualMachines | ForEach-Object { $_.vmName })
    Add-NewVMForRole -Role 'Proxy' -Domain $domainName -ConfigToModify $ConfigToModify -Quiet:$true | Out-Null
    # Tag the VM we just added so Remove-ProxyVMIfAutoAdded can safely
    # auto-remove it later if the user disables proxy. User-created Proxy
    # VMs are never tagged, so manual additions are preserved.
    $newVM = $ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'Proxy' -and $existingNames -notcontains $_.vmName } | Select-Object -First 1
    if ($newVM) {
        $newVM | Add-Member -MemberType NoteProperty -Name '_autoAddedByProxy' -Value $true -Force
        # Drop any stale validation messages that reference this newly-added
        # VM name. They can only have come from a previous validation pass
        # (different config shape) and would mislead the user.
        Clear-StaleValidationMessagesForVM -VmName $newVM.vmName
        # write-log above is wiped by the menu's clear-screen; the banner is
        # the only channel the user actually gets to read.
        $optedIn = @($ConfigToModify.virtualMachines | Where-Object { -not $_.hidden -and $_.PSObject.Properties.Name -contains 'useProxy' -and [bool]$_.useProxy } | ForEach-Object { $_.vmName })
        $because = 'the domain proxy defaults'
        if ($optedIn.Count -gt 0) { $because = "useProxy=true on $($optedIn -join ', ')" }
        Add-ErrorMessage -Warning -property 'useProxy' -message "Added Proxy VM $($newVM.vmName) to $domainName because of $because. Deleting the Proxy VM turns useProxy off everywhere."
    }
}

function Remove-ProxyVMIfAutoAdded {
    # Counterpart to Add-ProxyVMIfMissing: when nothing in the config opts
    # into the proxy any longer, remove any Proxy VM that we previously
    # auto-added. Only removes VMs tagged with _autoAddedByProxy and not
    # already deployed in the domain, so user-created Proxy VMs are preserved.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.virtualMachines) { return }
    if (Test-ConfigNeedsProxy -ConfigToModify $ConfigToModify) { return }

    $domainName = if ($ConfigToModify.vmOptions) { $ConfigToModify.vmOptions.domainName } else { $null }
    $deployedNames = @()
    if ($domainName) {
        try {
            $deployedNames = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | ForEach-Object { $_.vmName })
        } catch {}
    }

    $toRemove = @($ConfigToModify.virtualMachines | Where-Object {
        $_.role -eq 'Proxy' -and
        $_.PSObject.Properties['_autoAddedByProxy'] -and
        $_._autoAddedByProxy -and
        ($deployedNames -notcontains $_.vmName)
    })
    foreach ($vm in $toRemove) {
        write-log "[Proxy] Proxy no longer enabled - auto-removing previously auto-added Proxy VM '$($vm.vmName)'"
        Remove-VMFromConfig -vmName $vm.vmName -ConfigToModify $ConfigToModify
    }
}
