# This file must be saved with UTF-8 BOM. createGuestDscZip.ps1 loads it under PS 5.1, which needs the BOM to parse Unicode.
function Rename-VirtualMachine {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "Base Property Object")]
        [Object] $vm,
        [Parameter(Mandatory = $false, HelpMessage = "NewName - AutoGenerated if blank")]
        [string] $newName
    )

    if ($vm.ExistingVM) {
        return
    }
    $rename = $true
    if (-not $newName) {
        $rename = $false
        $newName = Get-NewMachineName -vm $vm
        if ($($vm.vmName) -ne $newName) {
            $rename = $true
            Write-Log -Activity "Proposing to rename $($vm.vmName) to $($newName) due to configuration changes" -NoNewLine
            $response = Read-YesOrNoWithTimeout -Prompt "Rename $($vm.vmName) to $($newName)? (Y/n)" -HideHelp -Default "y"
            if (-not [String]::IsNullOrWhiteSpace($response)) {
                if ($response.ToLowerInvariant() -eq "n" -or $response.ToLowerInvariant() -eq "no") {
                    $rename = $false
                }
            }
        }
    }

    if ($rename -eq $true) {

        foreach ($existing in $Global:Config.virtualMachines) {
            if ($existing.RemoteSQLVM -eq $vm.vmName) {
                $existing.RemoteSQLVM = $newName
            }
            if ($existing.remoteContentLibVM -eq $vm.vmName) {
                $existing.remoteContentLibVM = $newName
            }
            if ($existing.patchMyPCFileServer -eq $vm.vmName) {
                $existing.patchMyPCFileServer = $newName
            }
            if ($existing.FileServerVM -eq $vm.vmName) {
                $existing.FileServerVM = $newName
            }
            if ($existing.pullDPSourceDP -eq $vm.vmName) {
                $existing.pullDPSourceDP = $newName
            }
            if ($existing.wsusDataBaseServer -eq $vm.vmName) {
                $existing.wsusDataBaseServer = $newName
            }


        }
        $vm.vmName = $newName
        return $newName
    }

}

function Test-OsdNetworkHasDistributionPoint {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $Network,
        [Parameter(Mandatory = $true)]
        [object] $Config
    )

    $allVMs = @(Get-List2 -DeployConfig $Config)
    $allVMs += @($Config.virtualMachines | Where-Object { $null -ne $_ })
    if ($global:existingMachines) {
        $allVMs += @($global:existingMachines | Where-Object { $null -ne $_ })
    }

    foreach ($candidate in $allVMs) {
        if (($candidate.installDP -eq $true -or $candidate.enablePullDP -eq $true) -and
            (Get-OsdEffectiveNetwork -VM $candidate -Config $Config) -eq $Network) {
            return $true
        }
    }
    return $false
}

function Get-OsdPxePathsForNetwork {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)] [string] $Network,
        [Parameter(Mandatory = $true)] [object] $Config
    )

    # The VM being edited is not guaranteed to have been appended to the
    # config yet. Add a transient client so the shared resolver can judge the
    # proposed network without mutating authored state.
    $probeConfig = $Config | ConvertTo-Json -Depth 8 | ConvertFrom-Json
    if (-not ($probeConfig.virtualMachines | Where-Object {
                $_.role -eq 'OSDClient' -and (Get-OsdEffectiveNetwork -VM $_ -Config $probeConfig) -eq $Network
            })) {
        $probeConfig.virtualMachines += [pscustomobject]@{
            vmName = '__OSD_NETWORK_PROBE__'
            role = 'OSDClient'
            network = $Network
        }
    }
    $inventory = @(Get-List2 -DeployConfig $Config)
    $inventory += @($Config.virtualMachines | Where-Object { $_.hidden })
    if ($global:existingMachines) { $inventory += @($global:existingMachines) }
    $inventory += @($probeConfig.virtualMachines)
    return @(Get-OsdPxePaths -Config $probeConfig -Inventory $inventory | Where-Object {
            $_.clientNetwork -eq $Network
        })
}

function Get-OsdRelayDistributionPointCandidates {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)] [string] $Network,
        [Parameter(Mandatory = $true)] [object] $Config
    )

    # Existing VM notes carry LastKnownIP while hidden config entries omit it.
    # Prefer live inventory for candidate facts; config remains the fallback
    # for newly authored DPs (which normally lack a stable address until deploy).
    $allVMs = @(Get-List -Type VM -DomainName $Config.vmOptions.domainName -ErrorAction SilentlyContinue)
    if ($global:existingMachines) { $allVMs += @($global:existingMachines) }
    $allVMs += @(Get-List2 -DeployConfig $Config)
    $allVMs += @($Config.virtualMachines)
    $seen = @{}
    foreach ($candidate in $allVMs) {
        if (-not $candidate -or -not $candidate.vmName) { continue }
        $key = "$($candidate.vmName)".ToLowerInvariant()
        if ($seen.ContainsKey($key)) { continue }
        $seen[$key] = $true
        if (-not ($candidate.installDP -eq $true -or $candidate.enablePullDP -eq $true)) { continue }
        if ([string]::IsNullOrWhiteSpace("$($candidate.siteCode)")) { continue }
        $candidateNetwork = Get-OsdEffectiveNetwork -VM $candidate -Config $Config
        if ($candidateNetwork -eq $Network) { continue }

        $ipValues = @($candidate.AssignedIP, $candidate.LastKnownIP)
        if ($candidate.thisParams) {
            $ipValues += @($candidate.thisParams.AssignedIP, $candidate.thisParams.IPv4Address)
        }
        $ipValues = @($ipValues | ForEach-Object {
                $candidateIp = "$_" -replace '/\d+$', ''
                $parsedCandidateIp = $null
                if ($_ -and [System.Net.IPAddress]::TryParse($candidateIp, [ref]$parsedCandidateIp) -and
                    $parsedCandidateIp.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetwork) {
                    $parsedCandidateIp.IPAddressToString
                }
            } | Select-Object -Unique)
        if ($ipValues.Count -ne 1) { continue }

        [pscustomobject]@{
            VM = $candidate
            Network = "$candidateNetwork"
            SiteCode = "$($candidate.siteCode)"
            IPv4 = "$($ipValues[0])"
        }
    }
}

function Add-DhcpRelayForOsdNetwork {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)] [string] $Network,
        [Parameter(Mandatory = $true)] [object] $Config
    )

    $candidates = @(Get-OsdRelayDistributionPointCandidates -Network $Network -Config $Config)
    if ($candidates.Count -eq 0) {
        Write-RedX "No remote Distribution Point with one agreed stable IPv4 address is available."
        return $false
    }
    $candidateOptions = @($candidates | ForEach-Object {
            "$($_.VM.vmName) [site $($_.SiteCode), subnet $($_.Network), $($_.IPv4)]"
        })
    $selection = Get-Menu2 -MenuName "Relay PXE requests from $Network" `
        -Prompt 'Select the remote Distribution Point that will answer PXE' `
        -OptionArray $candidateOptions -Test:$false -Split
    if ([string]::IsNullOrWhiteSpace($selection) -or $selection -eq 'ESCAPE') { return $false }
    $target = $candidates | Where-Object { $_.VM.vmName -eq $selection } | Select-Object -First 1
    if (-not $target) { return $false }

    $originalVirtualMachines = $Config.virtualMachines | ConvertTo-Json -Depth 8 | ConvertFrom-Json
    $existingRelaySources = @($Config.virtualMachines)
    $existingRelaySources += @($global:existingMachines)
    $existingRelaySources += @(Get-List -Type VM -DomainName $Config.vmOptions.domainName -ErrorAction SilentlyContinue)
    $relays = @($existingRelaySources | Where-Object { $_.role -eq 'DHCPRelay' } |
        Group-Object -Property vmName | ForEach-Object { $_.Group | Select-Object -First 1 })
    if ($relays.Count -gt 1) {
        Write-RedX "Domain '$($Config.vmOptions.domainName)' has multiple DHCPRelay VMs: $(@($relays.vmName) -join ', ')."
        return $false
    }

    try {
        $relay = $null
        $relayIsExisting = $false
        if ($relays.Count -eq 1) {
            $relay = $relays[0] | ConvertTo-Json -Depth 8 | ConvertFrom-Json
            $relayIsExisting = [bool]($relay.hidden -or $relay.ExistingVM -or
                ($global:existingMachines | Where-Object { $_.vmName -eq $relay.vmName }))
        }
        else {
            $beforeNames = @($Config.virtualMachines | ForEach-Object { $_.vmName })
            $null = Add-NewVMForRole -Role 'DHCPRelay' -Domain $Config.vmOptions.domainName `
                -ConfigToModify $Config -Network $Config.vmOptions.network -Quiet:$true
            $relay = $Config.virtualMachines | Where-Object {
                $_.role -eq 'DHCPRelay' -and $beforeNames -notcontains $_.vmName
            } | Select-Object -First 1
            if (-not $relay) { throw 'the DHCPRelay VM was not created' }
        }

        $newMappings = @($relay.relayMappings | Where-Object {
                $null -ne $_ -and "$($_.clientNetwork)" -ne $Network
            })
        $newMappings += [pscustomobject]@{
            clientNetwork = $Network
            distributionPointVM = "$($target.VM.vmName)"
        }
        $relay | Add-Member -MemberType NoteProperty -Name relayMappings -Value @($newMappings) -Force

        if ($relayIsExisting) {
            $relay | Add-Member -MemberType NoteProperty -Name ExistingVM -Value $true -Force
            Add-ModifiedExistingVMToDeployConfig -VM $relay -ConfigToModify $Config -Hidden:$true
        }
        else {
            $configuredRelay = $Config.virtualMachines | Where-Object { $_.vmName -eq $relay.vmName } | Select-Object -First 1
            $configuredRelay.relayMappings = @($newMappings)
        }

        $resolved = @(Get-OsdPxePathsForNetwork -Network $Network -Config $Config)
        if ($resolved.Count -ne 1 -or $resolved[0].mode -ne 'Relay' -or
            $resolved[0].distributionPointVM -ne $target.VM.vmName) {
            $why = @($resolved | ForEach-Object { "$($_.mode): $($_.reason)" }) -join '; '
            throw "the saved mapping did not resolve to Relay ($why)"
        }

        # Keep the interactive existing-machine cache in sync only after the
        # hidden snapshot and resolver both succeeded.
        $sourceRelay = $global:existingMachines | Where-Object { $_.vmName -eq $relay.vmName } | Select-Object -First 1
        if ($sourceRelay) { $sourceRelay | Add-Member -MemberType NoteProperty -Name relayMappings -Value @($newMappings) -Force }
        Write-Log "Configured OSD PXE relay: $Network -> $($relay.vmName) -> $($target.VM.vmName) ($($target.SiteCode), $($target.IPv4))." -Success
        return $true
    }
    catch {
        $Config.virtualMachines = @($originalVirtualMachines)
        Write-RedX "Could not configure the DHCP relay for ${Network}: $($_.Exception.Message)"
        return $false
    }
}

function Resolve-OsdPxePathForNetwork {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)] [string] $Network,
        [Parameter(Mandatory = $true)] [object] $Config
    )

    while ($true) {
        $relayCandidates = @(Get-OsdRelayDistributionPointCandidates -Network $Network -Config $Config)
        $additionalOptions = [ordered]@{
            'D'  = "Install or enable a Distribution Point on $Network"
            'HD' = 'Uses the existing DP promotion and DP-only VM workflow'
        }
        if ($relayCandidates.Count -gt 0) {
            $additionalOptions['R'] = 'Relay PXE to an existing remote Distribution Point'
            $additionalOptions['HR'] = 'Uses one dedicated Ubuntu relay VM; Windows DHCP remains on the host'
        }
        $additionalOptions['B'] = 'Choose a different subnet'
        $additionalOptions['HB'] = 'Returns without changing the current PXE topology'

        $selection = Get-Menu2 -MenuName "OSD requires a PXE path on $Network" `
            -Prompt 'Choose a local Distribution Point, a remote relay target, or go back' `
            -OptionArray @() -AdditionalOptions $additionalOptions -Test:$false -Split
        if ([string]::IsNullOrWhiteSpace($selection) -or $selection -in @('B', 'ESCAPE')) { return $false }
        if ($selection -eq 'D' -and (Add-DistributionPointForOsdNetwork -Network $Network -Config $Config)) { return $true }
        if ($selection -eq 'R' -and (Add-DhcpRelayForOsdNetwork -Network $Network -Config $Config)) { return $true }
    }
}

function Get-OsdDistributionPointPromotionCandidates {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $Network,
        [Parameter(Mandatory = $true)]
        [object] $Config
    )

    $sources = @(
        [pscustomobject]@{ VMs = @($Config.virtualMachines | Where-Object { -not $_.hidden }); TrackChanges = $false }
        [pscustomobject]@{ VMs = @($global:existingMachines); TrackChanges = $true }
    )
    $seen = @{}

    foreach ($source in $sources) {
        foreach ($candidate in $source.VMs) {
            $vmName = "$($candidate.vmName)"
            if (-not $vmName) { continue }
            $key = $vmName.ToLowerInvariant()
            if ($seen.ContainsKey($key)) { continue }
            $seen[$key] = $true

            if ((Get-OsdEffectiveNetwork -VM $candidate -Config $Config) -ne $Network) { continue }
            if ($candidate.role -notin @('DomainMember', 'SiteSystem')) { continue }
            if ($candidate.installDP -eq $true -or $candidate.enablePullDP -eq $true) { continue }
            if ($candidate.sqlVersion -or $candidate.remoteSQLVM) { continue }

            $operatingSystem = "$($candidate.operatingSystem)"
            if ($operatingSystem -notlike 'Server *' -and $operatingSystem -notlike 'Windows 11*') { continue }

            [pscustomobject]@{
                VM           = $candidate
                TrackChanges = [bool]$source.TrackChanges
            }
        }
    }
}

function Select-OsdDistributionPointSiteCode {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $Network,
        [Parameter(Mandatory = $true)]
        [object] $Config,
        [Parameter(Mandatory = $false)]
        [object] $CandidateVM
    )

    $domain = "$($Config.vmOptions.domainName)"
    $sites = @(Get-EligiblePushSites -Config $Config -Domain $domain)
    if ($sites.Count -eq 0) {
        Write-RedX "A Distribution Point cannot be added because no Primary or Secondary site is available."
        return $null
    }

    $validSiteCodes = @($sites | ForEach-Object { "$($_.SiteCode)" })
    $lockedSiteCode = Get-PushClientSubnetLock -Subnet $Network -Config $Config -Domain $domain -DefaultNet $Config.vmOptions.network
    if (-not ($lockedSiteCode -and $validSiteCodes -contains "$lockedSiteCode")) { $lockedSiteCode = $null }

    $allVMs = @(Get-List2 -DeployConfig $Config)
    $allVMs += @($Config.virtualMachines | Where-Object { $_.hidden })
    if ($global:existingMachines) { $allVMs += @($global:existingMachines) }
    $assignedSiteCodes = @($allVMs | Where-Object {
            (Get-OsdEffectiveNetwork -VM $_ -Config $Config) -eq $Network -and
            ($_.pushClient -is [string]) -and $_.pushClient -and
            $validSiteCodes -contains "$($_.pushClient)"
        } | ForEach-Object { "$($_.pushClient)" } | Select-Object -Unique)
    if ($assignedSiteCodes.Count -gt 1) {
        Write-RedX "Subnet $Network has conflicting site assignments: $($assignedSiteCodes -join ', '). Resolve them before adding an OSD Distribution Point."
        return $null
    }

    $requiredSiteCode = $lockedSiteCode
    if ($assignedSiteCodes.Count -eq 1) {
        if ($requiredSiteCode -and $requiredSiteCode -ne $assignedSiteCodes[0]) {
            Write-RedX "Subnet $Network is owned by site $requiredSiteCode but contains a VM assigned to site $($assignedSiteCodes[0]). Resolve the conflict before adding an OSD Distribution Point."
            return $null
        }
        $requiredSiteCode = $assignedSiteCodes[0]
    }

    if ($CandidateVM -and $CandidateVM.role -eq 'SiteSystem' -and
        $CandidateVM.siteCode -and $validSiteCodes -contains "$($CandidateVM.siteCode)") {
        if ($requiredSiteCode -and $requiredSiteCode -ne "$($CandidateVM.siteCode)") {
            Write-RedX "SiteSystem '$($CandidateVM.vmName)' belongs to site $($CandidateVM.siteCode), but subnet $Network belongs to site $requiredSiteCode. Choose a different VM or create a new DP."
            return $null
        }
        return "$($CandidateVM.siteCode)"
    }
    if ($requiredSiteCode) {
        return "$requiredSiteCode"
    }

    $currentSiteCode = $null
    if ($CandidateVM) {
        foreach ($preferred in @($CandidateVM.siteCode, $CandidateVM.pushClient)) {
            if ($preferred -and ($validSiteCodes -contains "$preferred")) {
                $currentSiteCode = "$preferred"
                break
            }
        }
    }
    if (-not $currentSiteCode) {
        $matchingSite = $sites | Where-Object { $_.Network -eq $Network } | Select-Object -First 1
        if ($matchingSite) { $currentSiteCode = "$($matchingSite.SiteCode)" }
    }
    if (-not $currentSiteCode) {
        $currentSiteCode = "$((@($sites | Where-Object { $_.Role -eq 'Primary' }) + @($sites))[0].SiteCode)"
    }
    if ($sites.Count -eq 1) {
        return "$($sites[0].SiteCode)"
    }

    $siteOptions = @($sites | ForEach-Object { "$($_.SiteCode) [$($_.Role), $($_.Network)]" })
    $currentOption = $siteOptions | Where-Object { $_ -like "$currentSiteCode *" } | Select-Object -First 1
    if (-not $currentOption) { $currentOption = $currentSiteCode }
    $selection = Get-Menu2 -MenuName "Select the site that will own the DP on $Network" -Prompt "Select Primary or Secondary site" `
        -OptionArray $siteOptions -CurrentValue $currentOption -Test:$false -Split
    if ([string]::IsNullOrWhiteSpace($selection) -or $selection -eq 'ESCAPE') {
        return $null
    }
    return "$selection".Split(' ')[0]
}

function Set-OsdDistributionPointPromotionProperty {
    param (
        [Parameter(Mandatory = $true)]
        [object] $VM,
        [Parameter(Mandatory = $true)]
        [string] $Name,
        [Parameter(Mandatory = $false)]
        [AllowNull()]
        [object] $Value,
        [Parameter(Mandatory = $true)]
        [bool] $TrackChanges
    )

    $hasProperty = $VM.PSObject.Properties.Name -contains $Name
    if ($hasProperty -and $VM.$Name -eq $Value) { return }

    if ($TrackChanges) {
        $originalName = "$Name-Original"
        if ($VM.PSObject.Properties.Name -notcontains $originalName) {
            $originalValue = if ($hasProperty) { $VM.$Name } else { $null }
            $VM | Add-Member -MemberType NoteProperty -Name $originalName -Value $originalValue -Force
        }
    }
    $VM | Add-Member -MemberType NoteProperty -Name $Name -Value $Value -Force
}

function Enable-OsdDistributionPointOnCandidate {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [object] $Candidate,
        [Parameter(Mandatory = $true)]
        [string] $SiteCode,
        [Parameter(Mandatory = $true)]
        [object] $Config
    )

    $sourceVM = $Candidate.VM
    $trackChanges = [bool]$Candidate.TrackChanges
    $vm = $sourceVM
    if ($trackChanges) {
        $vm = $sourceVM | ConvertTo-Json -Depth 5 | ConvertFrom-Json
    }
    $previousRole = "$($vm.role)"
    if ($trackChanges -and $vm.PSObject.Properties.Name -notcontains 'ExistingVM') {
        $vm | Add-Member -MemberType NoteProperty -Name ExistingVM -Value $true -Force
    }

    Set-OsdDistributionPointPromotionProperty -VM $vm -Name role -Value 'SiteSystem' -TrackChanges:$trackChanges
    Set-OsdDistributionPointPromotionProperty -VM $vm -Name siteCode -Value $SiteCode -TrackChanges:$trackChanges
    Set-OsdDistributionPointPromotionProperty -VM $vm -Name installDP -Value $true -TrackChanges:$trackChanges
    Set-OsdDistributionPointPromotionProperty -VM $vm -Name enablePullDP -Value $false -TrackChanges:$trackChanges

    if ($previousRole -eq 'DomainMember') {
        foreach ($roleProperty in @('installMP', 'installSUP', 'installRP', 'installSMSProv')) {
            Set-OsdDistributionPointPromotionProperty -VM $vm -Name $roleProperty -Value $false -TrackChanges:$trackChanges
        }
    }
    Set-SiteSystemPropertiesForOperatingSystem -VirtualMachine $vm

    if ($trackChanges) {
        $null = Add-ModifiedExistingVMToDeployConfig -VM $vm -ConfigToModify $Config -Hidden:$true
        if (-not ($Config.virtualMachines | Where-Object { $_.vmName -eq $vm.vmName -and $_.hidden })) {
            Write-RedX "Could not persist the Distribution Point changes for deployed VM '$($vm.vmName)'."
            return $null
        }

        foreach ($propertyName in @($sourceVM.PSObject.Properties.Name)) {
            if ($vm.PSObject.Properties.Name -notcontains $propertyName) {
                $sourceVM.PSObject.Properties.Remove($propertyName)
            }
        }
        foreach ($property in $vm.PSObject.Properties) {
            $sourceVM | Add-Member -MemberType NoteProperty -Name $property.Name -Value $property.Value -Force
        }
        $vm = $sourceVM
    }
    return $vm
}

function Add-DistributionPointForOsdNetwork {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string] $Network,
        [Parameter(Mandatory = $true)]
        [object] $Config
    )

    while ($true) {
        $candidates = @(Get-OsdDistributionPointPromotionCandidates -Network $Network -Config $Config)
        $candidateOptions = @($candidates | ForEach-Object {
                $source = if ($_.TrackChanges) { 'deployed' } else { 'new' }
                "$($_.VM.vmName) [$source $($_.VM.role), $($_.VM.operatingSystem)]"
            })
        $additionalOptions = [ordered]@{
            'N'  = "Create a new Distribution Point VM on $Network"
            'HN' = 'Adds a DP-only SiteSystem VM on the selected subnet'
            'B'  = 'Choose a different subnet'
            'HB' = 'Returns to the OSDClient subnet picker without making changes'
        }

        $selection = Get-Menu2 -MenuName "OSD requires a Distribution Point on $Network" `
            -Prompt 'Select an existing VM for the DP role, create a new DP VM, or go back' `
            -OptionArray $candidateOptions -AdditionalOptions $additionalOptions -Test:$false -Split
        if ([string]::IsNullOrWhiteSpace($selection) -or $selection -in @('B', 'ESCAPE')) {
            return $false
        }

        if ($selection -eq 'N') {
            $siteCode = Select-OsdDistributionPointSiteCode -Network $Network -Config $Config
            if (-not $siteCode) { continue }

            $machineName = Add-NewVMForRole -Role 'SiteSystem' -Domain $Config.vmOptions.domainName `
                -ConfigToModify $Config -SiteCode $siteCode -Network $Network -ReturnMachineName:$true -DistributionPointOnly:$true
            $newDP = $Config.virtualMachines | Where-Object { $_.vmName -eq $machineName } | Select-Object -First 1
            if (-not $newDP) {
                Write-RedX "The new Distribution Point VM was not added. Choose another option."
                continue
            }
            $newDP.installDP = $true
            $newDP | Add-Member -MemberType NoteProperty -Name enablePullDP -Value $false -Force
            if ($newDP.PSObject.Properties.Name -contains 'installMP') { $newDP.installMP = $false }
            Set-SiteSystemPropertiesForOperatingSystem -VirtualMachine $newDP
            Write-Log "Added Distribution Point VM '$($newDP.vmName)' on $Network for site $siteCode." -Success
            return $true
        }

        $candidate = $candidates | Where-Object { $_.VM.vmName -eq $selection } | Select-Object -First 1
        if (-not $candidate) { continue }
        $siteCode = Select-OsdDistributionPointSiteCode -Network $Network -Config $Config -CandidateVM $candidate.VM
        if (-not $siteCode) { continue }

        $promotedVM = Enable-OsdDistributionPointOnCandidate -Candidate $candidate -SiteCode $siteCode -Config $Config
        if (-not $promotedVM) { continue }
        Write-Log "Enabled the Distribution Point role on '$($promotedVM.vmName)' on $Network for site $siteCode." -Success
        return $true
    }
}

function Select-OsdClientNetwork {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [object] $VM,
        [Parameter(Mandatory = $true)]
        [object] $Config
    )

    $currentNetwork = Get-OsdEffectiveNetwork -VM $VM -Config $Config
    while ($true) {
        $network = Select-Subnet -ConfigToCheck $Config -CurrentNetworkIsValid:$true -CurrentVM $VM
        if ([string]::IsNullOrWhiteSpace($network)) { return $currentNetwork }

        $allVMs = @(Get-List2 -DeployConfig $Config)
        $allVMs += @($Config.virtualMachines | Where-Object { $_.hidden })
        if ($global:existingMachines) { $allVMs += @($global:existingMachines) }
        $hasCmSite = @($allVMs | Where-Object { $_.role -in @('CAS', 'Primary', 'Secondary') }).Count -gt 0
        if (-not $hasCmSite) { return $network }

        if (Test-OsdNetworkHasDistributionPoint -Network $network -Config $Config) {
            return $network
        }
        $existingPath = @(Get-OsdPxePathsForNetwork -Network $network -Config $Config)
        if ($existingPath.Count -eq 1 -and $existingPath[0].mode -eq 'Relay') {
            Write-Log "Using stored OSD PXE relay: $network -> $($existingPath[0].relayVM) -> $($existingPath[0].distributionPointVM)." -Success
            return $network
        }
        if (Resolve-OsdPxePathForNetwork -Network $network -Config $Config) {
            return $network
        }
    }
}


function Get-NetworkForVM {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "VM Object")]
        [object] $vm,
        [Parameter(Mandatory = $false, HelpMessage = "Config to Modify")]
        [object] $ConfigToModify = $global:config,
        [Parameter(Mandatory = $false, HelpMessage = "If a new network isn't needed, return null")]
        [bool] $ReturnIfNotNeeded = $false
    )

    $currentNetwork = $ConfigToModify.vmOptions.Network
    if ($currentNetwork -eq "10.234.241.0") {
        return
    }
    if ($vm.Network) {
        $currentNetwork = $vm.Network
    }
    $SiteServers = get-list2 -deployConfig $ConfigToModify | Where-Object { ($_.Role -eq "Primary" -or $_.Role -eq "Secondary") -and $_.vmName -ne $vm.vmName }
    #$SiteServers | convertto-Json | Out-Host
    #$ConfigToModify  |convertto-Json | Out-Host
    #$Secondaries = get-list2 -deployConfig $ConfigToModify  | Where-Object {$_.Role -eq "Secondary"}
    switch ($vm.role) {
        "Secondary" {
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "Primary" {
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "CAS" {
            $SiteServers = get-list2 -deployConfig $ConfigToModify | Where-Object { ($_.Role -eq "Primary" -or $_.Role -eq "Secondary" -or $_.Role -eq "CAS") -and $_.vmName -ne $vm.vmName }
            $SiteServers = $SiteServers | Where-Object { -not ($_.Role -eq "Primary" -and $_.ParentSiteCode -eq $vm.SiteCode) }
            if ($currentNetwork -in $SiteServers.network) {
                #Write-host "$CurrentNetwork is in $($SiteServers.network)"

                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$false -CurrentVM $vm
            }
            else {
                if (-not $ReturnIfNotNeeded) {
                    return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
                }
            }
        }
        "PassiveSite" {
            $SS = Get-SiteServerForSiteCode -siteCode $vm.SiteCode -deployConfig $ConfigToModify -type VM
            if ($ss.network -ne $currentNetwork) {
                return $ss.Network
            }
        }
        "SiteSystem" {
            # Interactive edits must allow deliberate remote-DP placement. Creation
            # uses ReturnIfNotNeeded to inherit the site server's subnet by default.
            if (-not $ReturnIfNotNeeded) {
                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm
            }

            # sitesAndNetworks maps exactly one subnet per site code, so a DP/MP left
            # on the default network sits inside another site's boundary.
            # Get-SiteServerForSiteCode throws when the site code resolves to nothing.
            try {
                $SS = Get-SiteServerForSiteCode -siteCode $vm.SiteCode -deployConfig $ConfigToModify -type VM
            }
            catch {
                Write-Log "Get-NetworkForVM: no site server found for site code '$($vm.SiteCode)'; leaving $($vm.vmName) on $currentNetwork." -LogOnly
                return $null
            }
            if ($ss.network -ne $currentNetwork) {
                return $ss.Network
            }
        }
        Default {
            if (-not $ReturnIfNotNeeded) {
                if ($vm.role -eq 'OSDClient') {
                    return Select-OsdClientNetwork -VM $vm -Config $ConfigToModify
                }
                return Select-Subnet -config $configToModify -CurrentNetworkIsValid:$true -CurrentVM $vm

            }
        }
    }

    return $null
}

function Add-NewVMForRole {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true, HelpMessage = "Role")]
        [String] $Role,
        [Parameter(Mandatory = $true, HelpMessage = "Domain Name")]
        [String] $Domain,
        [Parameter(Mandatory = $false, HelpMessage = "Config to Modify")]
        [object] $ConfigToModify = $global:config,
        [Parameter(Mandatory = $false, HelpMessage = "Force VM Name. Otherwise auto-generated")]
        [string] $Name = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Force VM Name for 2nd Node. Otherwise auto-generated")]
        [string] $Name2 = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Parent Side Code if this is a Primary or Secondary in a Hierarchy")]
        [string] $parentSiteCode = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Override Network")]
        [string] $network = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Site Code if this is a PassiveSite or a DPMP")]
        [string] $SiteCode = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Override default OS")]
        [string] $OperatingSystem = $null,
        [Parameter(Mandatory = $false, HelpMessage = "Return Created Machine Name")]
        [bool] $ReturnMachineName = $false,
        [Parameter(Mandatory = $false, HelpMessage = "Quiet Mode")]
        [bool] $Quiet = $false,
        [Parameter(Mandatory = $false, HelpMessage = "Test Mode")]
        [bool] $test = $false,
        [Parameter(Mandatory = $false, HelpMessage = "True if this is the Secondary SQLAO Node")]
        [bool] $secondSQLAO = $false,
        [Parameter(Mandatory = $false, HelpMessage = "Create a SiteSystem with only the Distribution Point role enabled")]
        [bool] $DistributionPointOnly = $false
    )


    $oldConfig = $configToModify | ConvertTo-Json -Depth 5 | ConvertFrom-Json
    Write-Verbose "[Add-NewVMForRole] Start Role: $Role Domain: $Domain Config: $ConfigToModify OS: $OperatingSystem SiteCode: $SiteCode ParentSiteCode: $parentSiteCode Network: $network"

    if ([string]::IsNullOrWhiteSpace($OperatingSystem)) {
        if ($role -in @('Proxy', 'DHCPRelay')) {
            # Fixed-purpose infrastructure roles are always Linux -- no OS choice.
            $OperatingSystem = "Ubuntu Server 24.04 LTS"
        }
        elseif ($role -eq "LinuxServer") {
            # Generic Linux server: same base image as Proxy, DHCP networking.
            $OperatingSystem = "Ubuntu Server 24.04 LTS"
        }
        elseif ($role -eq "LinuxClient") {
            # Ubuntu Desktop workstation (UbuntuDesktop2404.vhdx) -- no OS choice.
            # Without this branch a LinuxClient falls into the final else, where
            # $role.Contains("Client") pre-fills operatingSystem from
            # domainDefaults.DefaultClientOS (a Windows client OS), so a new
            # LinuxClient would show up as Windows 10/11.
            $OperatingSystem = "Ubuntu Desktop 24.04 LTS"
        }
        elseif ($role -eq "WorkgroupMember" -or $role -eq "AADClient" -or $role -eq "InternetClient") {
            $OSList = Get-SupportedOperatingSystemsForRole -role $role
            if (-not $OSList -or $OSList.Count -eq 0) {
                Write-Host
                Write-RedX "No supported operating systems available for role '$role'. If running in Offline Mode, ensure base images are downloaded first."
                return
            }
            $operatingSystem = "Windows 10 Latest (64-bit)"
            if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                if ($OSList -contains $ConfigToModify.domainDefaults.DefaultClientOS) {
                    $operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
                }
                else {
                    Write-Log "Default client OS '$($ConfigToModify.domainDefaults.DefaultClientOS)' is not available (Offline Mode?). Prompting for selection." -Warning
                    $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM" -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false -CurrentValue $operatingSystem
                    if ($OperatingSystem -eq "ESCAPE" -or $OperatingSystem -eq "NOITEMS") {
                        return
                    }
                }
            }
            else {          
                Write-Log -Verbose "No Default OS defined" 
                $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM"  -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false -CurrentValue $operatingSystem
                if ($OperatingSystem -eq "ESCAPE" -or $OperatingSystem -eq "NOITEMS") {
                    return
                }
            }
        }
        else {
            $OSList = Get-SupportedOperatingSystemsForRole -role $role
            if ($role.Contains("Client")) {
                $DefaultOperatingSystem = "Windows 10 Latest (64-bit)"
                if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                    $operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
                }
            }
            else {
                $DefaultOperatingSystem = "Server 2022"
                if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                    $operatingSystem = $ConfigToModify.domainDefaults.DefaultServerOS
                }
            }
            if ($null -ne $OSList) {
                if (-not $OperatingSystem) {                        
                    Write-Log -Verbose "No Default OS defined" 
                    Write-Log -Activity "OS Version selection for new '$role' VM" -NoNewLine
                    $OperatingSystem = Get-Menu2 -MenuName "OS Version selection for new '$role' VM" -prompt "Select OS Version for new $role VM" -optionArray $OSList -Test:$false -CurrentValue $DefaultOperatingSystem
                    if ($OperatingSystem -eq "ESCAPE") {
                        $OperatingSystem = $DefaultOperatingSystem
                        return
                    }
                }
            }
        }
    }


    $actualRoleName = ($Role -split " ")[0]

    if ($role -eq "SqlServer") {
        $actualRoleName = "DomainMember"
    }

    $memory = "2GB"
    $vprocs = 2

    $installSSMS = $false
    if ($OperatingSystem.Contains("Server") -and ($role -notin ("DC", "BDC"))) {
        $memory = "3GB"
        $vprocs = 4
        $installSSMS = $true
        if ($ConfigToModify.domainDefaults.IncludeSSMSOnNONSQL -eq $false) {
            $installSSMS = $false
            if ($role -eq "SqlServer") {
                $installSSMS = $true
            }
        }
    }
    if ($OperatingSystem.Contains("Windows 11") -and ($role -notin ("DC", "BDC"))) {
        $memory = "4GB"
        
        $installSSMS = $false
    }

    $virtualMachine = [PSCustomObject]@{
        vmName          = $null
        role            = $actualRoleName
        operatingSystem = $OperatingSystem
        memory          = $memory
        virtualProcs    = $vprocs
        tpmEnabled      = $true
    }

    if ($role -eq "Proxy") {
        # Linux VM: no TPM, lightweight footprint, osFamily marker so
        # Test-VmIsLinux short-circuits the Windows create/validation paths.
        # 2GB/2vCPU is the floor: at 1GB/1vCPU a Proxy booting alongside 20+
        # Windows VMs could fail to reach userspace at all.
        $virtualMachine.PSObject.Properties.Remove('tpmEnabled')
        $virtualMachine.memory = "2GB"
        $virtualMachine.virtualProcs = 2
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'osFamily' -Value 'Linux' -Force
        # Optional xrdp + lightweight desktop for graphical login. When true,
        # New-LinuxVirtualMachine installs xrdp/xfce4 via cloud-init and the
        # RDCMan file includes an entry that auto-logs in as vmbuildadmin
        # using the same LocalAdmin password as the rest of the lab.
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'enableRDP' -Value $false -Force
    }

    if ($role -eq 'DHCPRelay') {
        # The management NIC is the only NIC represented by cloud-init.
        # Mapping NICs are reconciled after first boot and keyed by MAC.
        $virtualMachine.PSObject.Properties.Remove('tpmEnabled')
        $virtualMachine.memory = '2GB'
        $virtualMachine.virtualProcs = 2
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'osFamily' -Value 'Linux' -Force
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'relayMappings' -Value @() -Force
    }

    if ($role -eq "LinuxServer") {
        # Generic Linux VM: no TPM, DHCP networking (default in New-LinuxSeedIso),
        # slightly larger footprint than Proxy since it's a general-purpose box.
        # osFamily=Linux makes Test-VmIsLinux short-circuit the Windows create/
        # validation paths the same way it does for Proxy.
        $virtualMachine.PSObject.Properties.Remove('tpmEnabled')
        $virtualMachine.memory = "2GB"
        $virtualMachine.virtualProcs = 2
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'osFamily' -Value 'Linux' -Force
        # Optional xrdp + xfce4 desktop (same toggle as Proxy).
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'enableRDP' -Value $false -Force
        # Optional realmd/SSSD join to the lab AD domain on first boot.
        # When true, New-LinuxVirtualMachine adds realmd packages + a
        # `realm join` runcmd to the cloud-init seed ISO. Default false
        # so the VM stands alone unless the user opts in.
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'joinDomain' -Value $false -Force
    }

    if ($role -eq "LinuxClient") {
        # Ubuntu Desktop workstation: real GNOME/GDM3/NetworkManager image
        # (UbuntuDesktop2404.vhdx) targeted at MDM/EDR testing (Intune for
        # Linux, Defender for Endpoint, Landscape, etc.). Heavier footprint
        # than LinuxServer since GNOME wants ~3GB to be usable, and the
        # baked-in xrdp/xorgxrdp service means RDP into a real Ubuntu
            # session works out of the box (no enableRDP cloud-init toggle
            # needed -- the existing toggle installs xfce4 which would clash
            # with GNOME on this image).
        $virtualMachine.PSObject.Properties.Remove('tpmEnabled')
        $virtualMachine.memory = "4GB"
        $virtualMachine.virtualProcs = 4
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'osFamily' -Value 'Linux' -Force
        # Optional realmd/SSSD join to the lab AD domain on first boot
        # (same helper as LinuxServer).
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'joinDomain' -Value $false -Force
    }

    if ($network) {
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
    }
    if ($role -notin ("OSDClient", "AADClient", "DC", "BDC", "Proxy", "DHCPRelay", "LinuxServer", "LinuxClient")) {
        #Match Windows 10 or 11
        if ($operatingSystem.Contains("Windows 1")) {
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'useFakeWSUSServer' -Value $false -force
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $installSSMS -force
    }

   

    $existingDPMP = $null
    $NewFSServer = $null
    switch ($Role) {
        "WSUS" {
            # Default to 8GB: a standalone WSUS uses the Windows Internal Database (WID)
            # co-located with the WsusPool app pool, and the first full catalog sync can
            # push their combined working set past 4-5GB. Below 8GB the pool hits its
            # memory-recycle cap mid-sync and the sync is OOM/recycle-killed (503),
            # which the WID+WSUS memory validation flags as a hard failure. Default to
            # 8GB so a freshly-added WSUS passes validation out of the box.
            $virtualMachine.Memory = "8GB"
            #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $true
            if (-not (Set-WsusDedicatedContentDisk -VirtualMachine $virtualMachine)) {
                Write-RedX "Could not allocate a dedicated WSUS content disk. Cancelling"
                return
            }
            #if (-not $SiteCode) {
            #    $SiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
            #    if ($test) {
            #        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            #    }
            #    else {
            #        Get-SiteCodeMenu -property $virtualMachine -name "siteCode" -CurrentValue $SiteCode -ConfigToCheck $configToModify
            #        if (-not $virtualMachine.SiteCode) {
            #            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $false -force
            #        }
            #    }
            #}
            #else {
            #    #write-log "Adding new DPMP for sitecode $newSiteCode"
            #    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            #}

        }
        "SqlServer" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion  -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "E:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.Memory = "7GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $virtualMachine.tpmEnabled = $false
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value "LocalSystem" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value "LocalSystem" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
        }
        "SQLAO" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "E:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.Memory = "7GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $virtualMachine.tpmEnabled = $false
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force

        }
        "CAS" {
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "F:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value "E:\ConfigMgr" -force
            $disk = [PSCustomObject]@{"E" = "250GB"; "F" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $enableSUP = if ($ConfigToModify.domainDefaults.EnableSUPOnSiteServers) { $true } else { $false }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $enableSUP -force
            if ($enableSUP) {
                if (-not (Set-WsusDedicatedContentDisk -VirtualMachine $virtualMachine)) {
                    Write-RedX "Could not allocate a dedicated WSUS content disk. Cancelling"
                    return
                }
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installRP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr CAS" -force
            $virtualMachine.Memory = "10GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem   
            if (-not $test) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }                
            }
        }
        "Primary" {
            if ($parentSiteCode) {
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'parentSiteCode' -Value $parentSiteCode
            }
            $SqlVersion = "SQL Server 2022"

            if ($ConfigToModify.domainDefaults.DefaultSqlVersion) {
                $SqlVersion = $ConfigToModify.domainDefaults.DefaultSqlVersion
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlVersion' -Value $SqlVersion -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceName' -Value "MSSQLSERVER" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlInstanceDir' -Value "F:\SQL" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'sqlPort' -Value "1433" -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSSMS' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value "E:\ConfigMgr" -force
            $disk = [PSCustomObject]@{"E" = "600GB"; "F" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $enableSUP = if ($ConfigToModify.domainDefaults.EnableSUPOnSiteServers) { $true } else { $false }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $enableSUP -force
            if ($enableSUP) {
                if (-not (Set-WsusDedicatedContentDisk -VirtualMachine $virtualMachine)) {
                    Write-RedX "Could not allocate a dedicated WSUS content disk. Cancelling"
                    return
                }
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installRP' -Value $false -force
            # A Primary can optionally host its own DP/MP in addition to dedicated
            # SiteSystem DPs (e.g. to serve as a Pull DP source). Default both off.
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installDP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installMP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr Primary Site" -force

            $virtualMachine.Memory = "10GB"
            $virtualMachine.virtualProcs = 8
            $virtualMachine.operatingSystem = $OperatingSystem
            $existingDPMP = ($ConfigToModify.virtualMachines | Where-Object { $_.installDP -or $_.enablePullDP } | Measure-Object).Count
            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }

        }
        "Secondary" {
            $virtualMachine.memory = "3GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'parentSiteCode' -Value $parentSiteCode -force
            $virtualMachine.operatingSystem = $OperatingSystem
            $newSiteCode = Get-NewSiteCode $Domain -Role $actualRoleName -ConfigToCheck $ConfigToModify
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $newSiteCode -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value 'E:\ConfigMgr' -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installSUP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteName' -Value "ConfigMgr Secondary Site" -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }

        }
        "PassiveSite" {
            $virtualMachine.memory = "3GB"
            $NewFSServer = $true
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmInstallDir' -Value 'E:\ConfigMgr' -force
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force

            if (-not $test -and (-not $network)) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig  -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }
        }
        "WorkgroupMember" {}
        "InternetClient" {}
        "AADClient" {}
        "StandaloneRootCA" {
            $virtualMachine.Memory = "2GB"
            $virtualMachine.virtualProcs = 2
        }
        "DomainMember" {
            if ($OperatingSystem -notlike "*Server*") {
                $users = get-list2 -DeployConfig $oldConfig | Where-Object { $_.domainUser } | Select-Object -ExpandProperty domainUser -Unique
                [int]$i = 1
                $userPrefix = "$($oldConfig.vmOptions.prefix)".ToLower() + "user"
                $userNoPrefix = "user"
                while ($true) {
                    $preferredUserName = $userPrefix + $i
                    $noPrefixUserName = $userNoPrefix + $i
                    if ($users -contains $preferredUserName -or $users -contains $noPrefixUserName) {
                        write-log -verbose "$preferredUserName already exists Trying next"
                        $i++
                    }
                    else {
                        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'domainUser' -Value $noPrefixUserName -force
                        break
                    }
                }
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installOffice' -Value $false -force
            }
        }
        "DomainMember (Server)" {}
        "DomainMember (Client)" {
            if ($OperatingSystem -like "*Server*") {
                if ($ConfigToModify.domainDefaults.DefaultClientOS) {
                    $virtualMachine.operatingSystem = $ConfigToModify.domainDefaults.DefaultClientOS
                }
                else {
                    $virtualMachine.operatingSystem = "Windows 10 Latest (64-bit)"
                }
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'useFakeWSUSServer' -Value $false -force
            }
            else {
                $virtualMachine.operatingSystem = $OperatingSystem
            }

            $users = get-list2 -DeployConfig $oldConfig | Where-Object { $_.domainUser } | Select-Object -ExpandProperty domainUser -Unique
            [int]$i = 1
            $userPrefix = "$($oldConfig.vmOptions.prefix)".ToLower() + "user"
            $userNoPrefix = "user"
            while ($true) {
                $preferredUserName = $userPrefix + $i
                $noPrefixUserName = $userNoPrefix + $i
                if ($users -contains $preferredUserName -or $users -contains $noPrefixUserName) {
                    write-log -verbose "$preferredUserName already exists Trying next"
                    $i++
                }
                else {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'domainUser' -Value $noPrefixUserName -force
                    break
                }

            }

            $virtualMachine.Memory = "2GB"
            if ($virtualMachine.operatingSystem.Contains("Windows 11") ) {
                $virtualMachine.Memory = "4GB"
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installOffice' -Value $false -force
        }
        "OSDClient" {
            $virtualMachine.memory = "2GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'vmGeneration' -Value "2" -force
            $virtualMachine.PsObject.Members.Remove('operatingSystem')
        }
        "SiteSystem" {
            $virtualMachine.memory = "4GB"
            $disk = [PSCustomObject]@{"E" = "250GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallDP' -Value $true -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallMP' -Value (-not $DistributionPointOnly) -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallSUP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallRP' -Value $false -force
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'InstallSMSProv' -Value $false -force
            if (-not $SiteCode) {
                $SiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
                if ($test) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
                }
                else {
                    #This sets the virtualmachine.Sitecode property.. Make sure to read this back in when done.
                    Get-SiteCodeMenu -property $virtualMachine -name "siteCode" -CurrentValue $SiteCode -ConfigToCheck $configToModify -test:$false
                }

                if (-not $($virtualMachine.SiteCode)) {
                    Write-RedX "Could not add SiteCode to SiteSystem $($virtualMachine.vmName). Cancelling"
                    return
                }

                if ((get-RoleForSitecode -ConfigToCheck $ConfigToModify -siteCode $virtualMachine.siteCode) -eq "CAS") {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installDP' -Value $false -force
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'installMP' -Value $false -force
                }

                if ($virtualMachine.installDP) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'enablePullDP' -Value $false
                }
            }
            else {
                $virtualMachine | Add-Member -MemberType NoteProperty -Name 'siteCode' -Value $SiteCode -Force
            }
            # Needed when expanding an existing domain
            $siteCode = $virtualMachine.siteCode
            if ((get-RoleForSitecode -ConfigToCheck $ConfigToModify -siteCode $siteCode) -eq "Secondary") {
                $virtualMachine.installMP = $false
            }
            Set-SiteSystemPropertiesForOperatingSystem -VirtualMachine $virtualMachine
            if (-not $network) {
                $network = Get-NetworkForVM -vm $virtualMachine -ConfigToModify $oldConfig -ReturnIfNotNeeded:$true
                if ($network) {
                    $virtualMachine | Add-Member -MemberType NoteProperty -Name 'network' -Value $network -force
                }
            }
        }
        "FileServer" {
            $virtualMachine.memory = "3GB"
            $disk = [PSCustomObject]@{"E" = "600GB"; "F" = "200GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'additionalDisks' -Value $disk -force
            $virtualMachine.tpmEnabled = $false
        }
        "DC" {
            $virtualMachine.memory = "4GB"
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'ForestTrust' -Value "NONE" -force
            $virtualMachine.tpmEnabled = $false
        }
        "BDC" {
            $virtualMachine.memory = "4GB"
            $virtualMachine.tpmEnabled = $false
        }
    }

    if ([string]::IsNullOrWhiteSpace($Name)) {
        if ($virtualMachine.InstallMP -or $virtualMachine.InstallDP) {
            $machineName = Get-NewMachineName -ConfigToCheck $oldConfig -vm $virtualMachine
        }
        else {
            $machineName = Get-NewMachineName -ConfigToCheck $oldConfig -vm $virtualMachine
        }
        Write-Verbose "Machine Name Generated $machineName"
    }
    else {
        $machineName = $Name
    }
    $virtualMachine.vmName = $machineName

    if ($null -eq $ConfigToModify.VirtualMachines) {
        $ConfigToModify | Add-Member -MemberType NoteProperty -Name "VirtualMachines" -Value @() -Force
    }

    # Add BitLocker property if BLM is enabled and VM has TPM + client OS.
    # Non-domain roles (InternetClient, WorkgroupMember, AADClient) never receive BLM policy.
    if ($virtualMachine.tpmEnabled -and $ConfigToModify.cmOptions -and $ConfigToModify.cmOptions.EnableBLM -and $role -notin 'InternetClient', 'WorkgroupMember', 'AADClient') {
        $isClientOS = $virtualMachine.operatingSystem -and $virtualMachine.operatingSystem -like "Windows 1*"
        $virtualMachine | Add-Member -MemberType NoteProperty -Name "BitLocker" -Value ([bool]$isClientOS) -Force
    }

    # Add pushClient property for DomainMember and site system VMs.
    # Default from domainDefaults:
    #   client OS DomainMember        -> PushCMClientToClients
    #   server OS DomainMember (+SQL) -> PushCMClientToServers
    #   site system roles             -> PushCMClientToSiteSystems
    # Use the normalized role ($actualRoleName) here, NOT the raw $Role: the
    # role menu passes "DomainMember (Client)" / "DomainMember (Server)" /
    # "SqlServer", all of which normalize to "DomainMember". Gating on the raw
    # $Role silently skipped pushClient for every client (the "(Client)" suffix
    # made '$role -eq DomainMember' false), so the property never appeared.
    $siteSystemRoles = @('Primary', 'CAS', 'Secondary', 'SiteSystem', 'PassiveSite')
    if ($actualRoleName -eq 'DomainMember' -or $actualRoleName -in $siteSystemRoles) {
        # Canonical per-role fallback matching Get-NewDomainDefaults
        # (NewDomain.ps1): Clients ON, Servers OFF, SiteSystems OFF. Site
        # servers install the CM client locally during CM setup, so they are
        # NOT a client-push target by default (a $true fallback here wrongly
        # turned pushClient ON for site servers on domains whose domainDefaults
        # predates the PushCMClientToSiteSystems key).
        if ($actualRoleName -in $siteSystemRoles) {
            $defaultKey = 'PushCMClientToSiteSystems'
            $defaultVal = $false
        }
        else {
            $isClientOS = $virtualMachine.operatingSystem -and $virtualMachine.operatingSystem -like "Windows 1*"
            if ($isClientOS) { $defaultKey = 'PushCMClientToClients'; $defaultVal = $true }
            else { $defaultKey = 'PushCMClientToServers'; $defaultVal = $false }
        }
        if ($ConfigToModify.domainDefaults -and ($null -ne $ConfigToModify.domainDefaults.$defaultKey)) {
            $defaultVal = [bool]$ConfigToModify.domainDefaults.$defaultKey
        }
        # pushClient stores a TARGET SITE CODE string (or $false). Resolve the
        # boolean default to a concrete site code (the site whose subnet matches
        # this VM, else the first Primary) so the new VM is consistent with the
        # site-code model. Falls back to $false / the boolean when no CM site
        # exists yet.
        $pushValue = $defaultVal
        if ($defaultVal) {
            $domForPush = $null
            if ($ConfigToModify.vmOptions) { $domForPush = $ConfigToModify.vmOptions.domainName }
            $eligiblePush = @(Get-EligiblePushSites -Config $ConfigToModify -Domain $domForPush)
            if ($eligiblePush.Count -gt 0) {
                $resolved = Resolve-PushClientSite -VM $virtualMachine -Config $ConfigToModify -Domain $domForPush -EligibleSites $eligiblePush
                if ($resolved) { $pushValue = $resolved } else { $pushValue = $false }
            }
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name "pushClient" -Value $pushValue -Force
    }

    # Add useProxy property for VMs that can sensibly route through the
    # domain's Squid proxy. Excludes the Proxy VM itself, DCs (DNS for the
    # domain itself), and StandaloneRootCA (offline, no networking). Both
    # Windows and Linux VMs are eligible -- Windows clients are configured
    # via Set-WindowsClientProxy over PSDirect, Linux clients via the Phase 3
    # roles/proxy-client bash module over SSH.
    # Default is seeded from one of two domainDefaults keys depending on the
    # VM's purpose:
    #   ConfigMgr site-system roles -> UseProxyForCM
    #   everything else (clients, plain DomainMembers, Linux) -> UseProxyForClients
    $proxyExcluded = @('Proxy', 'DC', 'BDC', 'StandaloneRootCA')
    if ($role -notin $proxyExcluded) {
        $cmRoles = @('CAS', 'Primary', 'Secondary', 'SiteSystem', 'PassiveSite', 'WSUS', 'SQLAO', 'FileServer')
        $useProxyKey = if ($role -in $cmRoles) { 'UseProxyForCM' } else { 'UseProxyForClients' }
        $useProxyDefault = $false
        if ($ConfigToModify.domainDefaults -and ($null -ne $ConfigToModify.domainDefaults.$useProxyKey)) {
            $useProxyDefault = [bool]$ConfigToModify.domainDefaults.$useProxyKey
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name "useProxy" -Value $useProxyDefault -Force
    }

    # Linux VMs run with static memory (Hyper-V Dynamic Memory on Linux is
    # flaky), so dynamicMinRam is meaningless for them -- don't add it.
    if (-not (Test-VmIsLinux -Vm $virtualMachine)) {
        if ($ConfigToModify.domainDefaults.UseDynamicMemory) {
            # SQL workloads need a higher floor; ConfigMgr SQL min server memory is 4GB
            $defaultMin = if ($virtualMachine.sqlVersion) { "4GB" } else { "1GB" }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'dynamicMinRam' -Value $defaultMin -force
        }
        else {
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'dynamicMinRam' -Value $virtualMachine.memory -force
        }
    }

    # Before adding, check if a VM with this name already exists
    $existingVM = $ConfigToModify.VirtualMachines | Where-Object { $_.vmName -eq $virtualMachine.vmName }
    if ($existingVM) {
        Write-Log -verbose "A VM with the name '$($virtualMachine.vmName)' already exists. Skipping add."
        if ($ReturnMachineName) {
            return $virtualMachine.vmName
        }
        else {
            return
        }
    }
    $ConfigToModify.virtualMachines += $virtualMachine

    if ($role -eq "Primary" -or $role -eq "CAS" -or $role -eq "PassiveSite" -or $role -eq "SiteSystem" -or $role -eq "Secondary") {
        # Post-migration shape: cmOptions live on each top-level site server VM
        # (CAS, or standalone Primary). Attach a block to the newly added VM
        # only when it is itself a top-level (CAS or Primary with no
        # parentSiteCode). When another top-level already exists in the
        # config, clone its cmOptions so the new hierarchy starts with the
        # same Version / PKI / BLM settings. Otherwise create defaults.
        # Child Primary under a CAS, SiteSystem, PassiveSite, and Secondary
        # all inherit at deploy time via New-DeployConfig rehydration.
        $isTopLevelAdd = ($role -in 'CAS', 'Primary') -and (-not $virtualMachine.parentSiteCode)
        if ($isTopLevelAdd -and -not $virtualMachine.cmOptions) {
            $existingTopLevel = $ConfigToModify.virtualMachines | Where-Object {
                $_.vmName -ne $virtualMachine.vmName -and
                $_.role -in 'CAS', 'Primary' -and -not $_.parentSiteCode -and $_.cmOptions
            } | Select-Object -First 1
            if ($existingTopLevel) {
                $newCmOptions = $existingTopLevel.cmOptions | ConvertTo-Json -Depth 5 -Compress | ConvertFrom-Json
            }
            else {
                # domainDefaults is a hint only. This is the one valid time to
                # consume it: the new top-level VM has no actual cmOptions yet.
                $latestVersion = Get-CmVersionWithHintFallback -DomainDefaults $ConfigToModify.domainDefaults -FallbackVersion (Get-CMLatestBaselineVersion)
                $newCmOptions = [PSCustomObject]@{
                    Version                   = $latestVersion
                    Install                   = $true
                    PrePopulateObjects        = $true
                    EVALVersion               = $false
                    #InstallSCP                = $true
                    OfflineSCP                = $false
                    OfflineSUP                = $false
                    UsePKI                    = $false
                    EnableBLM                 = $false
                    WsusImportBaseline        = $true
                }
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'cmOptions' -Value $newCmOptions -force
        }
    }

    if ($role -eq "CAS") {
        Add-NewVMForRole -Role Primary -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -Quiet:$Quiet -parentSiteCode $virtualMachine.SiteCode -network:$virtualMachine.network
    }

    #if ($existingPrimary -gt 0) {
    #    ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).parentSiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "CAS" } | Select-Object -First 1).siteCode
    #}

    if ($existingDPMP -eq 0) {
        if (-not $newSiteCode) {
            $newSiteCode = ($ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "Primary" } | Select-Object -First 1).SiteCode
        }
        if (-not $test) {
            Write-Host "New Primary server found. Adding new DPMP for sitecode $newSiteCode"
        }
        Add-NewVMForRole -Role SiteSystem -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -SiteCode $newSiteCode -Quiet:$Quiet
    }
    if ($Role -eq "PassiveSite") {
        $SiteCode = $virtualMachine.SiteCode

        $primaryNode = $ConfigToModify.virtualMachines | Where-Object { $_.Role -in ("Primary", "CAS") -and $_.siteCode -eq $SiteCode }
        if ($primaryNode.Role -eq "Primary") {                 
            $DPsForSiteCode = $ConfigToModify.virtualMachines | Where-Object { $_.Role -eq "SiteSystem" -and $_.siteCode -eq $SiteCode -and $_.installDP -eq $true }
            if (-not $DPsForSiteCode) {
                Add-NewVMForRole -Role SiteSystem -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -SiteCode $SiteCode -Quiet:$Quiet
            }
        }
    }
    if ($Role -eq "SQLAO" -and (-not $secondSQLAO)) {
        write-host "$($virtualMachine.VmName) is the 1st SQLAO"
        $SQLAONode = Add-NewVMForRole -Role SQLAO -Domain $Domain -ConfigToModify $ConfigToModify -OperatingSystem $OperatingSystem -Name $Name2 -secondSQLAO:$true -Quiet:$Quiet -ReturnMachineName:$true -network:$network
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'OtherNode' -Value $SQLAONode -force
        if ($test -eq $false ) {
            $FSName = select-FileServerMenu -ConfigToModify $ConfigToModify -HA:$false
            if ($FSName -eq "ESCAPE") {
                Remove-VMFromConfig -vmName $virtualMachine.vmName -ConfigToModify $ConfigToModify
                Remove-VMFromConfig -vmName $SQLAONode -ConfigToModify $ConfigToModify
                return
            }
            $virtualMachine | Add-Member -MemberType NoteProperty -Name 'fileServerVM' -Value $FSName -force
        }
        #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'SQLAgentAccount' -Value "SqlAgentUser"
        #$virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value "SqlServiceUser"
        $ClusterName = Get-NewMachineName -vm $virtualMachine -ConfigToCheck $ConfigToModify -ClusterName:$true -SkipOne:$true
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'ClusterName' -Value $ClusterName -force
        $AOName = Get-NewMachineName -vm $virtualMachine -ConfigToCheck $ConfigToModify -AOName:$true -SkipOne:$true
        $AGName = "SQL"
        if ($SiteCode) {
            $AGName = $siteCode
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'AlwaysOnGroupName' -Value $($AGName + " Availability Group") -force
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'AlwaysOnListenerName' -Value $AOName -force

        $ServiceAccount = "$($ClusterName)Svc"
        $AgentAccount = "$($ClusterName)Agent"

        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value $ServiceAccount -force
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value $AgentAccount -force

        $otherNode = $ConfigToModify.VirtualMachines | Where-Object { $_.vmName -eq $SQLAONode }
        $otherNode | Add-Member -MemberType NoteProperty -Name 'SqlServiceAccount' -Value $ServiceAccount -force
        $otherNode | Add-Member -MemberType NoteProperty -Name 'SqlAgentAccount' -Value $AgentAccount -force


    }
    if ($NewFSServer -eq $true) {
        #Get-PSCallStack | out-host
        $FSName = select-FileServerMenu -ConfigToModify $ConfigToModify -HA:$true
        if ($FSName -eq "ESCAPE") {
            Remove-VMFromConfig -vmName $virtualMachine.vmName -ConfigToModify $ConfigToModify
            return
        }
        $virtualMachine | Add-Member -MemberType NoteProperty -Name 'remoteContentLibVM' -Value $FSName
    }
    #Get-PSCallStack | out-host
    if (-not $Quiet) {
        Write-Host2 -ForegroundColor $Global:Common.Colors.GenConfigNotice "New Virtual Machine $machineName ($role) was added"
    }
    Write-verbose "[Add-NewVMForRole] Config: $ConfigToModify"
    if ($ReturnMachineName) {
        return $machineName
    }
}

function Add-OfflineRootCAVMIfMissing {
    # When pkiOptions.UseOfflineRoot is enabled but no Standalone Offline
    # Root CA exists - neither in the in-memory config nor already deployed
    # in the target domain - auto-add one so the user doesn't have to.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.vmOptions -or -not $ConfigToModify.vmOptions.domainName) { return }

    # Only proceed if pkiOptions.UseOfflineRoot is enabled
    $pkiOpts = $ConfigToModify.pkiOptions
    if (-not $pkiOpts -or -not $pkiOpts.UseOfflineRoot) { return }

    $existsInConfig = @($ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'StandaloneRootCA' }).Count -gt 0
    if ($existsInConfig) { return }

    $domainName = $ConfigToModify.vmOptions.domainName
    try {
        $existsInDomain = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | Where-Object { $_.role -eq 'StandaloneRootCA' }).Count -gt 0
        if ($existsInDomain) { return }
    } catch {}

    write-log "[OfflineRootCA] pkiOptions.UseOfflineRoot enabled but no StandaloneRootCA VM found - auto-adding one to domain $domainName"
    $existingNames = @($ConfigToModify.virtualMachines | ForEach-Object { $_.vmName })
    $rootOS = if ($ConfigToModify.domainDefaults.DefaultServerOS) { $ConfigToModify.domainDefaults.DefaultServerOS } else { 'Server 2022' }
    Add-NewVMForRole -Role 'StandaloneRootCA' -Domain $domainName -ConfigToModify $ConfigToModify -OperatingSystem $rootOS -Quiet:$true | Out-Null
    # Tag the VM we just added so Remove-OfflineRootCAVMIfAutoAdded can
    # safely auto-remove it later if the user toggles UseOfflineRoot off.
    # We never tag a user-created VM, so manual additions are preserved.
    $newVM = $ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'StandaloneRootCA' -and $existingNames -notcontains $_.vmName } | Select-Object -First 1
    if ($newVM) {
        $newVM | Add-Member -MemberType NoteProperty -Name '_autoAddedByOfflineRootCA' -Value $true -Force
        # Also update pkiOptions.OfflineRootCAVM if not already set
        if ($pkiOpts -and -not $pkiOpts.OfflineRootCAVM) {
            $pkiOpts.OfflineRootCAVM = $newVM.vmName
        }
        # Drop any stale validation messages referencing this newly-added VM
        # (see Add-ProxyVMIfMissing for the carryOver-staleness rationale).
        Clear-StaleValidationMessagesForVM -VmName $newVM.vmName
    }
}

function Clear-StaleValidationMessagesForVM {
    # Removes any entries from $global:GenConfigErrorMessages and
    # $global:PendingValidationErrors whose Message references the given VM
    # name. Called whenever an auto-add/auto-remove mutates the config so
    # stale messages from a previous validation pass (different config shape)
    # don't surface to the user via the carryOver mechanism in genconfig.ps1.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $VmName
    )

    if (-not $VmName) { return }
    $needle = "[$VmName]"

    if ($global:GenConfigErrorMessages) {
        $kept = @($global:GenConfigErrorMessages | Where-Object { $_.Message -notlike "*$needle*" })
        if ($kept.Count -ne $global:GenConfigErrorMessages.Count) {
            Write-Log "[Clear-StaleValidationMessagesForVM] Dropped $($global:GenConfigErrorMessages.Count - $kept.Count) stale msg(s) for $VmName from GenConfigErrorMessages" -LogOnly
            $global:GenConfigErrorMessages = $kept
        }
    }
    if ($global:PendingValidationErrors) {
        $kept = @($global:PendingValidationErrors | Where-Object { $_.Message -notlike "*$needle*" })
        if ($kept.Count -ne $global:PendingValidationErrors.Count) {
            Write-Log "[Clear-StaleValidationMessagesForVM] Dropped $($global:PendingValidationErrors.Count - $kept.Count) stale msg(s) for $VmName from PendingValidationErrors" -LogOnly
            $global:PendingValidationErrors = $kept
        }
    }
}

function Remove-OfflineRootCAVMIfAutoAdded {
    # Counterpart to Add-OfflineRootCAVMIfMissing: when pkiOptions.UseOfflineRoot
    # is disabled, remove any StandaloneRootCA VM that we previously auto-added.
    # We only remove VMs tagged with _autoAddedByOfflineRootCA, so user-created
    # Root CA VMs are preserved. We also skip removal if the VM is already
    # deployed in the domain.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.virtualMachines) { return }

    # Only auto-remove when pkiOptions.UseOfflineRoot is disabled
    $pkiOpts = $ConfigToModify.pkiOptions
    $offlineRootEnabled = $pkiOpts -and $pkiOpts.UseOfflineRoot
    if ($offlineRootEnabled) { return }

    $domainName = if ($ConfigToModify.vmOptions) { $ConfigToModify.vmOptions.domainName } else { $null }
    $deployedNames = @()
    if ($domainName) {
        try {
            $deployedNames = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | ForEach-Object { $_.vmName })
        } catch {}
    }

    $toRemove = @($ConfigToModify.virtualMachines | Where-Object {
        $_.role -eq 'StandaloneRootCA' -and
        $_.PSObject.Properties['_autoAddedByOfflineRootCA'] -and
        $_._autoAddedByOfflineRootCA -and
        ($deployedNames -notcontains $_.vmName)
    })
    foreach ($vm in $toRemove) {
        write-log "[OfflineRootCA] UseOfflineRoot disabled - auto-removing previously auto-added StandaloneRootCA VM '$($vm.vmName)'"
        Remove-VMFromConfig -vmName $vm.vmName -ConfigToModify $ConfigToModify
    }
}

function Test-ConfigNeedsProxy {
    # Returns $true iff any non-hidden VM in the config has useProxy=$true.
    # domainDefaults.UseProxyFor* are seed-only hints used by Add-NewVMForRole
    # to populate the per-VM useProxy at creation time; they are NOT consulted
    # here. If every VM has useProxy=$false, the config does not need a proxy,
    # regardless of what the domain default says.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [object] $ConfigToModify
    )

    foreach ($vm in @($ConfigToModify.virtualMachines)) {
        if ($vm.hidden) { continue }
        if ($vm.PSObject.Properties.Name -contains 'useProxy' -and [bool]$vm.useProxy) {
            return $true
        }
    }
    return $false
}

function Disable-ProxyOptIn {
    # Clears every proxy opt-in in the config so a Proxy VM the user just
    # deleted is not immediately re-added by Add-ProxyVMIfMissing on the next
    # menu pass. Returns what was flipped so the caller can report it.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    $flipped = New-Object System.Collections.Generic.List[string]
    if (-not $ConfigToModify) { return $flipped.ToArray() }

    foreach ($vm in @($ConfigToModify.virtualMachines)) {
        if (-not $vm) { continue }
        if ($vm.PSObject.Properties.Name -contains 'useProxy' -and [bool]$vm.useProxy) {
            $vm.useProxy = $false
            $flipped.Add([string]$vm.vmName)
        }
    }

    # Seed-only hints: left true, the next VM added would opt in and pull a
    # replacement Proxy VM straight back into the config.
    if ($ConfigToModify.domainDefaults) {
        foreach ($key in @('UseProxyForClients', 'UseProxyForCM')) {
            if ($ConfigToModify.domainDefaults.PSObject.Properties.Name -contains $key -and [bool]$ConfigToModify.domainDefaults.$key) {
                $ConfigToModify.domainDefaults.$key = $false
                $flipped.Add("domainDefaults.$key")
            }
        }
    }

    return $flipped.ToArray()
}

function Add-ProxyVMIfMissing {
    # When the in-memory config opts into the proxy (domainDefaults.UseProxyFor*
    # or any per-VM useProxy=$true) but no Proxy VM exists -- neither in the
    # config nor already deployed in the target domain -- auto-add a Linux
    # Proxy VM so the user doesn't have to. Counterpart to
    # Remove-ProxyVMIfAutoAdded.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.vmOptions -or -not $ConfigToModify.vmOptions.domainName) { return }
    if (-not (Test-ConfigNeedsProxy -ConfigToModify $ConfigToModify)) { return }

    $existsInConfig = @($ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'Proxy' }).Count -gt 0
    if ($existsInConfig) { return }

    $domainName = $ConfigToModify.vmOptions.domainName
    try {
        $existsInDomain = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | Where-Object { $_.role -eq 'Proxy' }).Count -gt 0
        if ($existsInDomain) { return }
    } catch {}

    write-log "[Proxy] Proxy is enabled (domainDefaults or per-VM useProxy) but no Proxy VM found - auto-adding one to domain $domainName"
    $existingNames = @($ConfigToModify.virtualMachines | ForEach-Object { $_.vmName })
    Add-NewVMForRole -Role 'Proxy' -Domain $domainName -ConfigToModify $ConfigToModify -Quiet:$true | Out-Null
    # Tag the VM we just added so Remove-ProxyVMIfAutoAdded can safely
    # auto-remove it later if the user disables proxy. User-created Proxy
    # VMs are never tagged, so manual additions are preserved.
    $newVM = $ConfigToModify.virtualMachines | Where-Object { $_.role -eq 'Proxy' -and $existingNames -notcontains $_.vmName } | Select-Object -First 1
    if ($newVM) {
        $newVM | Add-Member -MemberType NoteProperty -Name '_autoAddedByProxy' -Value $true -Force
        # Drop any stale validation messages that reference this newly-added
        # VM name. They can only have come from a previous validation pass
        # (different config shape) and would mislead the user.
        Clear-StaleValidationMessagesForVM -VmName $newVM.vmName
        # write-log above is wiped by the menu's clear-screen; the banner is
        # the only channel the user actually gets to read.
        $optedIn = @($ConfigToModify.virtualMachines | Where-Object { -not $_.hidden -and $_.PSObject.Properties.Name -contains 'useProxy' -and [bool]$_.useProxy } | ForEach-Object { $_.vmName })
        $because = 'the domain proxy defaults'
        if ($optedIn.Count -gt 0) { $because = "useProxy=true on $($optedIn -join ', ')" }
        Add-ErrorMessage -Warning -property 'useProxy' -message "Added Proxy VM $($newVM.vmName) to $domainName because of $because. Deleting the Proxy VM turns useProxy off everywhere."
    }
}

function Remove-ProxyVMIfAutoAdded {
    # Counterpart to Add-ProxyVMIfMissing: when nothing in the config opts
    # into the proxy any longer, remove any Proxy VM that we previously
    # auto-added. Only removes VMs tagged with _autoAddedByProxy and not
    # already deployed in the domain, so user-created Proxy VMs are preserved.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $false)]
        [object] $ConfigToModify = $global:config
    )

    if (-not $ConfigToModify) { return }
    if (-not $ConfigToModify.virtualMachines) { return }
    if (Test-ConfigNeedsProxy -ConfigToModify $ConfigToModify) { return }

    $domainName = if ($ConfigToModify.vmOptions) { $ConfigToModify.vmOptions.domainName } else { $null }
    $deployedNames = @()
    if ($domainName) {
        try {
            $deployedNames = @(Get-List -Type VM -DomainName $domainName -ErrorAction SilentlyContinue | ForEach-Object { $_.vmName })
        } catch {}
    }

    $toRemove = @($ConfigToModify.virtualMachines | Where-Object {
        $_.role -eq 'Proxy' -and
        $_.PSObject.Properties['_autoAddedByProxy'] -and
        $_._autoAddedByProxy -and
        ($deployedNames -notcontains $_.vmName)
    })
    foreach ($vm in $toRemove) {
        write-log "[Proxy] Proxy no longer enabled - auto-removing previously auto-added Proxy VM '$($vm.vmName)'"
        Remove-VMFromConfig -vmName $vm.vmName -ConfigToModify $ConfigToModify
    }
}
